"""
WebSocket consumers for TeleICU real-time streaming.

VitalsConsumer — pushes live vitals for a single patient or the aggregated TeleICU stream.
AlertsConsumer — pushes threshold breach alerts to all subscribed dashboards.
SignalConsumer — WebRTC signaling relay with multi-room support.
"""
import json
import logging
from channels.generic.websocket import AsyncWebsocketConsumer
from channels.layers import get_channel_layer
from asgiref.sync import async_to_sync

logger = logging.getLogger(__name__)


# ── Notification helpers (called from sync views) ───────────────────────

def notify_pharmacy_queue(hospital_id, payload):
    """Push a prescription update to all pharmacy queue clients."""
    channel_layer = get_channel_layer()
    if channel_layer:
        async_to_sync(channel_layer.group_send)(
            f'pharmacy_queue_{hospital_id}',
            {
                'type': 'pharmacy_queue_update',
                'data': payload,
            },
        )


def notify_lab_queue(hospital_id, payload):
    """Push a lab order update to all lab queue clients."""
    channel_layer = get_channel_layer()
    if channel_layer:
        async_to_sync(channel_layer.group_send)(
            f'lab_queue_{hospital_id}',
            {
                'type': 'lab_queue_update',
                'data': payload,
            },
        )


class VitalsConsumer(AsyncWebsocketConsumer):
    """Stream vitals — single patient or aggregated TeleICU feed.

    Clients connecting to /ws/vitals/<patient_id>/ receive vitals for that
    one patient.  Clients connecting to /ws/teleicu/vitals/ receive the
    aggregated vitals stream for all monitored patients.
    """

    async def connect(self):
        patient_id = self.scope['url_route']['kwargs'].get('patient_id')
        if patient_id:
            self.patient_id = patient_id
            self.room_group_name = f'vitals_{self.patient_id}'
        else:
            self.room_group_name = 'teleicu_vitals'

        await self.channel_layer.group_add(
            self.room_group_name,
            self.channel_name,
        )
        await self.accept()

    async def disconnect(self, close_code):
        await self.channel_layer.group_discard(
            self.room_group_name,
            self.channel_name,
        )

    async def receive(self, text_data):
        """Server pushes vitals; clients do not send data upstream."""
        pass

    async def vitals_update(self, event):
        """Handler for 'vitals_update' messages broadcast from Celery tasks."""
        await self.send(text_data=json.dumps(event['data']))


class SignalConsumer(AsyncWebsocketConsumer):
    """WebRTC signaling relay with multi-room support.

    Clients connect to /ws/signal/<room_name>/ and exchange SDP
    offers/answers and ICE candidates within that room.
    Falls back to a default 'signal_room' if no room is specified.
    """

    async def connect(self):
        self.room_name = self.scope['url_route']['kwargs'].get(
            'room_name', 'signal_room'
        )
        self.room_group_name = f'signal_{self.room_name}'

        await self.channel_layer.group_add(
            self.room_group_name,
            self.channel_name,
        )
        await self.accept()
        logger.info("Signal client connected to room '%s'", self.room_name)

    async def disconnect(self, close_code):
        await self.channel_layer.group_discard(
            self.room_group_name,
            self.channel_name,
        )
        logger.info("Signal client disconnected from room '%s'", self.room_name)

    async def receive(self, text_data):
        """Relay signaling messages to other peers in the room."""
        try:
            data = json.loads(text_data)
            await self.channel_layer.group_send(
                self.room_group_name,
                {
                    'type': 'signal_message',
                    'data': data,
                    'sender_channel': self.channel_name,
                },
            )
        except json.JSONDecodeError:
            logger.warning("Invalid signal message received")

    async def signal_message(self, event):
        """Forward signaling message to all other clients in the room."""
        if event.get('sender_channel') != self.channel_name:
            await self.send(text_data=json.dumps(event['data']))


class AlertsConsumer(AsyncWebsocketConsumer):
    """Broadcast real-time alerts (threshold breaches, etc.) to all
    connected clinical dashboards.

    Clients connect to /ws/alerts/ and receive JSON alert objects as
    soon as they are generated by the threshold engine.
    """

    async def connect(self):
        self.room_group_name = 'alerts'

        await self.channel_layer.group_add(
            self.room_group_name,
            self.channel_name,
        )
        await self.accept()

    async def disconnect(self, close_code):
        await self.channel_layer.group_discard(
            self.room_group_name,
            self.channel_name,
        )

    async def alert_push(self, event):
        """Handler for alert messages from the threshold engine."""
        await self.send(text_data=json.dumps(event['data']))


# ── Pharmacy Queue Consumer ─────────────────────────────────────────────

class PharmacyQueueConsumer(AsyncWebsocketConsumer):
    """Real-time pharmacy queue updates.

    Clients connect to /ws/pharmacy-queue/<hospital_id>/ and receive
    prescription updates (new, amended, cancelled) as they happen.
    """

    async def connect(self):
        self.hospital_id = self.scope['url_route']['kwargs'].get('hospital_id')
        if not self.hospital_id:
            await self.close()
            return
        self.room_group_name = f'pharmacy_queue_{self.hospital_id}'

        await self.channel_layer.group_add(
            self.room_group_name,
            self.channel_name,
        )
        await self.accept()

    async def disconnect(self, close_code):
        await self.channel_layer.group_discard(
            self.room_group_name,
            self.channel_name,
        )

    async def pharmacy_queue_update(self, event):
        """Handle pharmacy queue update messages."""
        await self.send(text_data=json.dumps(event['data']))


# ── Lab Queue Consumer ──────────────────────────────────────────────────

class LabQueueConsumer(AsyncWebsocketConsumer):
    """Real-time lab queue updates.

    Clients connect to /ws/lab-queue/<hospital_id>/ and receive
    lab order updates (new orders, status changes) as they happen.
    """

    async def connect(self):
        self.hospital_id = self.scope['url_route']['kwargs'].get('hospital_id')
        if not self.hospital_id:
            await self.close()
            return
        self.room_group_name = f'lab_queue_{self.hospital_id}'

        await self.channel_layer.group_add(
            self.room_group_name,
            self.channel_name,
        )
        await self.accept()

    async def disconnect(self, close_code):
        await self.channel_layer.group_discard(
            self.room_group_name,
            self.channel_name,
        )

    async def lab_queue_update(self, event):
        """Handle lab queue update messages."""
        await self.send(text_data=json.dumps(event['data']))
