"""
WebSocket consumers for TeleICU real-time streaming.

VitalsConsumer — pushes live vitals for a single patient to subscribed dashboards.
AlertsConsumer — pushes threshold breach alerts to all subscribed dashboards.
"""
import json
import logging
from channels.generic.websocket import AsyncWebsocketConsumer

logger = logging.getLogger(__name__)


class VitalsConsumer(AsyncWebsocketConsumer):
    """Stream vitals for a single patient.

    Clients connect to /ws/vitals/<patient_id>/ and receive JSON messages
    containing the latest vitals snapshot whenever the Celery task generates one.
    """

    async def connect(self):
        self.patient_id = self.scope['url_route']['kwargs']['patient_id']
        self.room_group_name = f'vitals_{self.patient_id}'

        await self.channel_layer.group_add(
            self.room_group_name,
            self.channel_name,
        )
        await self.accept()

    async def disconnect(self, close_code):
        await self.channel_layer.group_discard(
            self.room_group_name,
            self.channel_name,
        )

    async def receive(self, text_data):
        """Server pushes vitals; clients do not send data upstream."""
        pass

    async def vitals_update(self, event):
        """Handler for 'vitals_update' messages broadcast from Celery tasks.

        The 'event' dict carries:
            type (str)  → 'vitals_update'
            data (dict) → the vitals payload
        """
        await self.send(text_data=json.dumps(event['data']))


class SignalConsumer(AsyncWebsocketConsumer):
    """WebRTC signaling relay.

    Relays SDP offers/answers and ICE candidates between two peers
    (doctor dashboard ↔ patient endpoint). Uses a room-based grouping
    so both peers can exchange messages.
    """

    async def connect(self):
        self.room_name = 'signal_room'
        self.room_group_name = f'signal_{self.room_name}'

        await self.channel_layer.group_add(
            self.room_group_name,
            self.channel_name,
        )
        await self.accept()
        logger.info("Signal client connected")

    async def disconnect(self, close_code):
        await self.channel_layer.group_discard(
            self.room_group_name,
            self.channel_name,
        )
        logger.info("Signal client disconnected")

    async def receive(self, text_data):
        """Relay any signaling message (offer, answer, ICE candidate)
        to the other peer in the room."""
        try:
            data = json.loads(text_data)
            # Broadcast to group except sender
            await self.channel_layer.group_send(
                self.room_group_name,
                {
                    'type': 'signal_message',
                    'data': data,
                    'sender_channel': self.channel_name,
                },
            )
        except json.JSONDecodeError:
            logger.warning("Invalid signal message received")

    async def signal_message(self, event):
        """Forward signaling message to all other clients in the room."""
        # Don't echo back to sender
        if event.get('sender_channel') != self.channel_name:
            await self.send(text_data=json.dumps(event['data']))


class AlertsConsumer(AsyncWebsocketConsumer):
    """Broadcast real-time alerts (threshold breaches, etc.) to all
    connected clinical dashboards.

    Clients connect to /ws/alerts/ and receive JSON alert objects as
    soon as they are generated by the threshold engine.
    """

    async def connect(self):
        self.room_group_name = 'alerts'

        await self.channel_layer.group_add(
            self.room_group_name,
            self.channel_name,
        )
        await self.accept()

    async def disconnect(self, close_code):
        await self.channel_layer.group_discard(
            self.room_group_name,
            self.channel_name,
        )

    async def alert_push(self, event):
        """Handler for alert messages from the threshold engine."""
        await self.send(text_data=json.dumps(event['data']))
