"""
Medication and lab order extraction from AI Scribe clinical notes.

Parses structured markdown notes (generated by the specialty prompt templates)
to identify prescribed medications and ordered lab tests, then validates
them against the hospital's DrugInventory and TestPanel catalogs.
"""
import logging
import re
from decimal import Decimal

from .models import DrugInventory, Dispensation
from .models.clinical import Medication
from .models.lab import LabOrder, TestPanel

logger = logging.getLogger(__name__)

# ── Medication Patterns ──────────────────────────────────────────────────────
# Expected format in the Treatment Plan section of an AI Scribe note:
#
#   1. Tab[let] <Drug Name> <Dosage> <Frequency> [x<Duration>] [<Qty>] [— <notes>]
#   2. Inj[ection] <Drug Name> <Dosage> <Frequency>
#   3. Caps[ule] <Drug Name> <Dosage> <Frequency>
#   4. Syrup <Drug Name> <Dosage> <Frequency> [x<Duration>]
#   5. <Drug Name> <Dosage> <Frequency> [x<Duration>]

DOSAGE_RE = re.compile(
    r'(\d+(?:\.\d+)?\s*(?:mg|mcg|g|ml|IU|units?|tablets?|tabs?|drops?))',
    re.IGNORECASE
)

FREQUENCY_MAP = {
    'OD': 'Once daily',
    'BD': 'Twice daily',
    'TDS': 'Three times daily',
    'QDS': 'Four times daily',
    'HS': 'At bedtime',
    'SOS': 'As needed',
    'PRN': 'As needed',
    'STAT': 'Immediately',
    'MANE': 'In the morning',
    'NOCTE': 'At night',
    'OM': 'In the morning',
    'ON': 'At night',
    'QID': 'Four times daily',
    'TID': 'Three times daily',
    'BID': 'Twice daily',
    'QD': 'Once daily',
    'Q4H': 'Every 4 hours',
    'Q6H': 'Every 6 hours',
    'Q8H': 'Every 8 hours',
    'Q12H': 'Every 12 hours',
    'WEEKLY': 'Once weekly',
}

DURATION_RE = re.compile(r'x\s*(\d+)\s*(day|days|week|weeks|month|months)?', re.IGNORECASE)
QUANTITY_RE = re.compile(r'(?:no\.|#|qty|quantity)\s*:?\s*(\d+)', re.IGNORECASE)

# ── Lab Test Patterns ────────────────────────────────────────────────────────
# Look for test panel names in the Treatment Plan and Investigations sections

UNIT_PRICE_DEFAULT = Decimal('0')


def extract_medications(note_text: str, encounter, hospital):
    """Parse the structured note and extract medication mentions.

    Returns a list of dicts:
        {
            'matched': bool,
            'drug_name': str,
            'dosage': str,
            'frequency': str,
            'duration': str,
            'quantity': int,
            'unit_price': Decimal,
            'inventory_item_id': str | None,
            'created': Medication | None,
        }

    When ``matched`` is True the drug was found in DrugInventory.
    When ``created`` is not None the record was already persisted.
    """
    results = []
    treatment_plan = _extract_section(note_text, 'Treatment Plan')

    if not treatment_plan:
        logger.info('No Treatment Plan section found in note')
        return results

    # Split into lines and look for medication-like entries
    lines = treatment_plan.split('\n')
    for line in lines:
        line = line.strip()
        if not line or len(line) < 5:
            continue

        # Skip numbered list items that look like referrals / procedures
        if _is_non_medication_line(line):
            continue

        drug_name = _extract_drug_name(line)
        if not drug_name:
            continue

        dosage = _extract_dosage(line)
        frequency = _extract_frequency(line)
        duration_str = _extract_duration(line)
        quantity = _extract_quantity(line, dosage, frequency, duration_str)

        # Try to match against DrugInventory
        inventory_item = _match_drug_inventory(drug_name, hospital)
        unit_price = inventory_item.unit_price if inventory_item else UNIT_PRICE_DEFAULT

        results.append({
            'matched': inventory_item is not None,
            'drug_name': drug_name,
            'dosage': dosage or '',
            'frequency': frequency or '',
            'duration': duration_str or '',
            'quantity': quantity,
            'unit_price': unit_price,
            'inventory_item_id': str(inventory_item.id) if inventory_item else None,
            'inventory_stock': int(inventory_item.quantity) if inventory_item else 0,
        })

    return results


def extract_lab_tests(note_text: str, encounter, hospital):
    """Parse the structured note and extract lab test mentions.

    Returns a list of dicts:
        {
            'matched': bool,
            'test_name': str,
            'test_panel_id': str | None,
            'price': Decimal,
        }
    """
    results = []

    # Check both Treatment Plan and Investigations sections
    treatment_plan = _extract_section(note_text, 'Treatment Plan') or ''
    investigations = _extract_section(note_text, 'Investigations') or ''
    combined = treatment_plan + '\n' + investigations

    if not combined.strip():
        return results

    # Get all active test panels for this hospital
    panels = list(TestPanel.objects.filter(hospital=hospital, is_active=True))

    for panel in panels:
        # Check if panel name or short name appears in the text
        names_to_check = [panel.name.lower(), panel.short_name.lower()]
        names_to_check = [n for n in names_to_check if n]

        found = False
        for name in names_to_check:
            if name and (name in combined.lower()):
                found = True
                break

        if found:
            results.append({
                'matched': True,
                'test_name': f'{panel.short_name or panel.name}',
                'test_panel_id': str(panel.id),
                'price': float(panel.price) if panel.price else 0,
            })

    return results


def create_medications(results, encounter, hospital, created_by=None):
    """Persist Medication and Dispensation records from extraction results.

    Only creates records where ``matched`` is True (drug found in inventory).
    Returns the list of created Medication instances.
    """
    created = []
    for r in results:
        if not r['matched']:
            continue
        if r.get('created'):
            created.append(r['created'])
            continue

        med = Medication.objects.create(
            encounter=encounter,
            drug_name=r['drug_name'],
            dosage=r['dosage'],
            frequency=r['frequency'],
            duration=r['duration'],
            quantity=r['quantity'] or 1,
            unit_price=r['unit_price'],
            is_active=True,
            hospital=hospital,
            prescribed_by=created_by,
        )

        # Auto-create PENDING Dispensation for pharmacy queue
        Dispensation.objects.create(
            medication=med,
            encounter=encounter,
            patient=encounter.patient,
            drug_name=med.drug_name,
            dosage=med.dosage,
            quantity_dispensed=0,
            status='PENDING',
            hospital=hospital,
        )

        r['created'] = str(med.id)
        created.append(med)

    return created


def create_lab_orders(results, encounter, hospital, ordered_by=None):
    """Persist LabOrder records from extraction results.

    Returns the list of created LabOrder instances.
    """
    created = []
    for r in results:
        if not r['matched']:
            continue
        if r.get('created'):
            created.append(r['created'])
            continue

        try:
            panel = TestPanel.objects.get(id=r['test_panel_id'], hospital=hospital)
        except TestPanel.DoesNotExist:
            continue

        lo = LabOrder.objects.create(
            patient=encounter.patient,
            encounter=encounter,
            test_panel=panel,
            ordered_by=ordered_by,
            priority='ROUTINE',
            status='ORDERED',
            hospital=hospital,
        )
        r['created'] = str(lo.id)
        created.append(lo)

    return created


# ── Internal helpers ─────────────────────────────────────────────────────────


def _extract_section(note_text: str, heading: str) -> str:
    """Extract the content of a markdown section by heading name."""
    # Match "## Treatment Plan" or "**Treatment Plan**" etc.
    patterns = [
        rf'##\s*{heading}\s*\n(.*?)(?=\n##\s|\Z)',
        rf'\*\*{heading}\*\*\s*\n(.*?)(?=\n\*\*|\Z)',
        rf'{heading}[:\n]+(.*?)(?=\n\n|\Z)',
    ]
    for pat in patterns:
        m = re.search(pat, note_text, re.DOTALL | re.IGNORECASE)
        if m:
            return m.group(1).strip()
    return ''


def _is_non_medication_line(line: str) -> bool:
    """Check if a line is likely not a medication entry."""
    non_med_keywords = [
        'refer', 'follow-up', 'followup', 'diet', 'exercise', 'advice',
        'review', 'admit', 'discharge', 'counsel', 'lifestyle', 'rest',
        'saline', 'iv fluids', 'physiotherapy', 'surgery', 'investigation',
    ]
    lower = line.lower()
    for kw in non_med_keywords:
        if kw in lower:
            return True
    return False


def _extract_drug_name(line: str) -> str | None:
    """Extract drug name from a treatment plan line.

    Handles patterns:
      - Tab Amoxicillin 250mg TDS x5 days
      - 1. Tab Paracetamol 500mg SOS
      - Inj Ceftriaxone 1g IV BD
      - Atorvastatin 10mg OD
    """
    # Remove leading numbering
    line = re.sub(r'^\s*[\d]+[.)]\s*', '', line).strip()

    # Remove dosage suffix to get just the drug name
    # Strategy: take the first word(s) before a dosage-like pattern
    words = line.split()
    drug_words = []
    for w in words:
        # Check if this word looks like a dosage (e.g., "250mg", "500mg", "5mg")
        if re.match(r'^\d+(?:\.\d+)?\s*(?:mg|mcg|g|ml|IU|units?|tablets?|tabs?|drops?)$', w, re.IGNORECASE):
            break
        # Check for common form prefixes
        if w.lower() in ('tab', 'tablet', 'caps', 'capsule', 'inj', 'injection',
                         'syrup', 'syp', 'ointment', 'cream', 'gel', 'drop',
                         'spray', 'inhaler', 'sachet', 'lotio', 'lotion'):
            continue
        drug_words.append(w)

    if not drug_words:
        return None

    drug_name = ' '.join(drug_words).strip(' ,;:.-')
    return drug_name if drug_name else None


def _extract_dosage(line: str) -> str:
    """Extract dosage string."""
    m = DOSAGE_RE.search(line)
    if m:
        return m.group(1)
    return ''


def _extract_frequency(line: str) -> str:
    """Extract and normalize the frequency."""
    # Check for known abbreviations
    for abbr, full in FREQUENCY_MAP.items():
        # Match word boundary or after slash
        pat = rf'(?:^|[\s,/]){abbr}(?:[\s,/]|$)'
        if re.search(pat, line, re.IGNORECASE):
            return full
    return ''


def _extract_duration(line: str) -> str:
    """Extract duration like 'x5 days' or 'x2 weeks'."""
    m = DURATION_RE.search(line)
    if m:
        days = m.group(1)
        unit = m.group(2) or 'days'
        return f'{days} {unit}'
    return ''


def _extract_quantity(line: str, dosage: str, frequency: str, duration: str) -> int:
    """Estimate the quantity of medication needed.

    Tries explicit quantity first, then estimates from frequency and duration.
    """
    # Check for explicit quantity
    m = QUANTITY_RE.search(line)
    if m:
        return int(m.group(1))

    # Estimate: frequency times per day × duration in days
    if frequency and duration:
        freq_per_day = {
            'Once daily': 1, 'Twice daily': 2, 'Three times daily': 3,
            'Four times daily': 4, 'Every 4 hours': 6, 'Every 6 hours': 4,
            'Every 8 hours': 3, 'Every 12 hours': 2, 'Once weekly': 0,
        }
        fpd = freq_per_day.get(frequency, 0)
        dur_match = re.search(r'(\d+)', duration)
        if fpd > 0 and dur_match:
            days = int(dur_match.group(1))
            return fpd * days

    return 1


def _match_drug_inventory(drug_name: str, hospital):
    """Find the best matching DrugInventory item for a drug name.

    Uses case-insensitive substring matching:
      1. Exact name match
      2. Name starts with drug_name (or vice versa)
      3. Name contains drug_name
    """
    items = DrugInventory.objects.filter(
        hospital=hospital, is_active=True
    ).select_related('drug')

    if not items.exists():
        return None

    clean_name = drug_name.lower().strip()

    for item in items:
        item_name = item.drug.name.lower().strip() if item.drug else item.name.lower().strip()
        if item_name == clean_name:
            return item

    # Partial match
    for item in items:
        item_name = item.drug.name.lower().strip() if item.drug else item.name.lower().strip()
        if clean_name in item_name or item_name in clean_name:
            return item

    return None
