# Generated by Django 6.0.6 on 2026-06-09 16:45

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_a', models.CharField(db_index=True, max_length=200)),
                ('drug_b', models.CharField(db_index=True, max_length=200)),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('major', 'Major'), ('contraindicated', 'Contraindicated')], max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('mechanism', models.TextField(blank=True, default='')),
                ('recommendation', models.TextField(blank=True, default='')),
                ('source', models.CharField(blank=True, default='', max_length=50)),
                ('cached_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['drug_a', 'drug_b'], name='medos_drugi_drug_a_08fa64_idx'), models.Index(fields=['severity'], name='medos_drugi_severit_d50329_idx')],
                'unique_together': {('drug_a', 'drug_b')},
            },
        ),
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('encounter_type', models.CharField(choices=[('OPD', 'Outpatient'), ('IPD', 'Inpatient'), ('EMERGENCY', 'Emergency'), ('TELEICU', 'TeleICU'), ('HOME', 'Home Visit')], default='OPD', max_length=20)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=20)),
                ('department', models.CharField(blank=True, default='', max_length=100)),
                ('chief_complaint', models.TextField(blank=True, default='')),
                ('clinical_notes', models.TextField(blank=True, default='')),
                ('diagnosis', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encounters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_type', models.CharField(choices=[('OPD', 'OPD Consultation'), ('PHARMACY', 'Pharmacy'), ('LAB', 'Lab Test'), ('IPD', 'Inpatient')], max_length=20)),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=18.0, help_text='GST percentage', max_digits=5)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='medos.encounter')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='medos.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=200)),
                ('generic_name', models.CharField(blank=True, default='', max_length=200)),
                ('brand_name', models.CharField(blank=True, default='', max_length=200)),
                ('dosage', models.CharField(help_text='e.g., 500mg', max_length=100)),
                ('frequency', models.CharField(help_text='e.g., Twice daily', max_length=100)),
                ('duration', models.CharField(blank=True, default='', help_text='e.g., 7 days', max_length=100)),
                ('route', models.CharField(default='Oral', max_length=50)),
                ('instructions', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('prescribed_at', models.DateTimeField(auto_now_add=True)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='medos.encounter')),
                ('prescribed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-prescribed_at'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hospital_patient_id', models.CharField(blank=True, help_text='External ID from legacy HMIS', max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, default='', max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=1)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('address', models.TextField(blank=True, default='')),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('pincode', models.CharField(blank=True, default='', max_length=10)),
                ('abha_id', models.CharField(blank=True, help_text='Ayushman Bharat Health Account ID', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('VITALS', 'Vitals Threshold'), ('DDI', 'Drug Interaction'), ('RISK', 'Risk Level Change'), ('SYSTEM', 'System Alert')], max_length=20)),
                ('severity', models.CharField(choices=[('INFO', 'Informational'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESOLVED', 'Resolved')], default='ACTIVE', max_length=20)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='medos.encounter')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='medos.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='medos.patient'),
        ),
        migrations.AddField(
            model_name='encounter',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='medos.patient'),
        ),
        migrations.CreateModel(
            name='SyncEntry',
            fields=[
                ('record_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('model_name', models.CharField(choices=[('patient', 'Patient'), ('encounter', 'Encounter'), ('vitals', 'Vitals'), ('medication', 'Medication')], max_length=50)),
                ('jsonb_snapshot', models.JSONField(help_text='Y.js CRDT document stored as JSON')),
                ('version', models.IntegerField(default=1, help_text='Document schema version')),
                ('source', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='online', max_length=20)),
                ('role_snapshot_hash', models.CharField(blank=True, default='', help_text="SHA-256 hash of user's role at time of write", max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Sync entries',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CONFLICT', 'Conflict')], max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('reconcoled_at', models.DateTimeField(auto_now_add=True)),
                ('sync_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_logs', to='medos.syncentry')),
            ],
            options={
                'ordering': ['-reconcoled_at'],
            },
        ),
        migrations.CreateModel(
            name='Vitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('systolic_bp', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(300)])),
                ('diastolic_bp', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(200)])),
                ('heart_rate', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(300)])),
                ('respiratory_rate', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(100)])),
                ('temperature', models.FloatField(blank=True, help_text='Body temperature in Celsius', null=True, validators=[django.core.validators.MinValueValidator(30.0), django.core.validators.MaxValueValidator(45.0)])),
                ('oxygen_saturation', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(100)], verbose_name='SpO2')),
                ('weight', models.FloatField(blank=True, help_text='Weight in kg', null=True, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(300.0)])),
                ('height', models.FloatField(blank=True, help_text='Height in cm', null=True, validators=[django.core.validators.MinValueValidator(10.0), django.core.validators.MaxValueValidator(300.0)])),
                ('blood_glucose', models.IntegerField(blank=True, help_text='Blood glucose in mg/dL', null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(1000)])),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='medos.encounter')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Vitals',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['hospital_patient_id'], name='medos_patie_hospita_cb5835_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['phone'], name='medos_patie_phone_742513_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['first_name', 'last_name'], name='medos_patie_first_n_2307c9_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalalert',
            index=models.Index(fields=['alert_type', 'status'], name='medos_medic_alert_t_6043fc_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalalert',
            index=models.Index(fields=['patient'], name='medos_medic_patient_8669f3_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalalert',
            index=models.Index(fields=['-created_at'], name='medos_medic_created_88ea2c_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='medos_invoi_invoice_347cc5_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['patient', '-created_at'], name='medos_invoi_patient_142c87_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='medos_invoi_status_168586_idx'),
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['patient', '-created_at'], name='medos_encou_patient_8b81e9_idx'),
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['doctor', '-created_at'], name='medos_encou_doctor__0baab6_idx'),
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['status'], name='medos_encou_status_6dd6ef_idx'),
        ),
        migrations.AddIndex(
            model_name='syncentry',
            index=models.Index(fields=['model_name'], name='medos_synce_model_n_a1b529_idx'),
        ),
        migrations.AddIndex(
            model_name='syncentry',
            index=models.Index(fields=['-created_at'], name='medos_synce_created_86c56b_idx'),
        ),
        migrations.AddIndex(
            model_name='vitals',
            index=models.Index(fields=['encounter', '-recorded_at'], name='medos_vital_encount_6b92a5_idx'),
        ),
    ]
