# Generated by Django 6.0.6 on 2026-06-10 08:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medos', '0003_clinicalnote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='bed_number',
            field=models.CharField(blank=True, default='', help_text='Bed/ward assignment for IPD/ICU (e.g. ICU-05, 304-A)', max_length=20),
        ),
        migrations.AddField(
            model_name='encounter',
            name='care_sub_status',
            field=models.CharField(blank=True, default='', help_text='Secondary status text (e.g. "On Monitoring", "Under Care")', max_length=50),
        ),
        migrations.AddField(
            model_name='encounter',
            name='clinical_acuity',
            field=models.CharField(blank=True, choices=[('Critical', 'Critical'), ('Stable', 'Stable'), ('Observation', 'Observation')], default='', help_text='Clinical status badge', max_length=20),
        ),
        migrations.AddField(
            model_name='encounter',
            name='encounter_number',
            field=models.CharField(blank=True, help_text='Auto-generated human-readable ID (e.g. ENC-20260610-00042)', max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='encounter',
            name='follow_up_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encounter',
            name='location',
            field=models.CharField(blank=True, default='', help_text='Hospital branch / wing / floor', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='', help_text='Blood group / type', max_length=3),
        ),
        migrations.AddField(
            model_name='patient',
            name='profile_picture',
            field=models.URLField(blank=True, default='', help_text='URL to patient profile photo'),
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('test_name', models.CharField(db_index=True, max_length=200)),
                ('category', models.CharField(choices=[('HEMATOLOGY', 'Hematology'), ('BIOCHEMISTRY', 'Biochemistry'), ('MICROBIOLOGY', 'Microbiology'), ('PATHOLOGY', 'Pathology'), ('RADIOLOGY', 'Radiology'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('result_value', models.TextField(blank=True, default='')),
                ('reference_range', models.CharField(blank=True, default='', max_length=200)),
                ('unit', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('ORDERED', 'Ordered'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('REVIEWED', 'Reviewed')], default='ORDERED', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('resulted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to='medos.encounter')),
                ('ordered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-ordered_at'],
                'indexes': [models.Index(fields=['encounter', '-ordered_at'], name='medos_labre_encount_575dd2_idx'), models.Index(fields=['test_name'], name='medos_labre_test_na_2ff1fa_idx'), models.Index(fields=['status'], name='medos_labre_status_96cd35_idx')],
            },
        ),
    ]
