# Generated by Django 6.0.6 on 2026-06-10 11:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medos', '0004_emr_gap_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='insurance_id',
            field=models.CharField(blank=True, default='', help_text='Insurance / TPA policy number', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='insurance_provider',
            field=models.CharField(blank=True, default='', help_text='Insurance / TPA provider name', max_length=100),
        ),
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allergen', models.CharField(max_length=200)),
                ('reaction', models.TextField(blank=True, default='')),
                ('severity', models.CharField(choices=[('MILD', 'Mild'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe')], default='MILD', max_length=20)),
                ('onset_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('noted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='medos.patient')),
            ],
            options={
                'verbose_name_plural': 'Allergies',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient', 'allergen'], name='medos_aller_patient_2ae4ae_idx')],
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('icd10_code', models.CharField(blank=True, default='', help_text='ICD-10 code (e.g. I10, J45.0)', max_length=20)),
                ('condition_name', models.CharField(max_length=300)),
                ('onset_date', models.DateField(blank=True, null=True)),
                ('resolved_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RESOLVED', 'Resolved'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diagnosed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnoses', to='medos.encounter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='medos.patient')),
            ],
            options={
                'verbose_name_plural': 'Diagnoses',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient', 'status'], name='medos_diagn_patient_33301b_idx'), models.Index(fields=['icd10_code'], name='medos_diagn_icd10_c_914689_idx')],
            },
        ),
        migrations.CreateModel(
            name='ImagingResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('modality', models.CharField(choices=[('XRAY', 'X-Ray'), ('CT', 'CT Scan'), ('MRI', 'MRI'), ('USG', 'Ultrasound'), ('ECHO', 'Echocardiogram'), ('ECG', 'Electrocardiogram'), ('TMT', 'Treadmill Test'), ('MAMMO', 'Mammography'), ('PET', 'PET Scan'), ('OTHER', 'Other')], default='XRAY', max_length=10)),
                ('title', models.CharField(max_length=300)),
                ('findings', models.TextField(blank=True, default='')),
                ('impression', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('ORDERED', 'Ordered'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('REVIEWED', 'Reviewed')], default='ORDERED', max_length=20)),
                ('report_file', models.URLField(blank=True, default='', help_text='URL to uploaded report PDF/image')),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('resulted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imaging_results', to='medos.encounter')),
                ('ordered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imaging_orders', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imaging_results', to='medos.patient')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imaging_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-ordered_at'],
                'indexes': [models.Index(fields=['patient', '-ordered_at'], name='medos_imagi_patient_c5a2b9_idx'), models.Index(fields=['encounter'], name='medos_imagi_encount_81f366_idx'), models.Index(fields=['modality'], name='medos_imagi_modalit_07d80f_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_name', models.CharField(help_text='Name of test / imaging / procedure', max_length=300)),
                ('category', models.CharField(choices=[('LAB', 'Lab Test'), ('IMAGING', 'Imaging'), ('PROCEDURE', 'Procedure')], default='LAB', max_length=20)),
                ('status', models.CharField(choices=[('ORDERED', 'Ordered'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ORDERED', max_length=20)),
                ('clinical_notes', models.TextField(blank=True, default='')),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='medos.encounter')),
                ('ordered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_orders', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='medos.patient')),
            ],
            options={
                'ordering': ['-ordered_at'],
                'indexes': [models.Index(fields=['patient', '-ordered_at'], name='medos_servi_patient_6d2f35_idx'), models.Index(fields=['encounter'], name='medos_servi_encount_5425ac_idx'), models.Index(fields=['status'], name='medos_servi_status_fb9d42_idx')],
            },
        ),
    ]
