# Generated by Django 6.0.6 on 2026-06-10 11:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medos', '0005_patient_summary_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('goals', models.JSONField(blank=True, default=list, help_text='List of treatment goals')),
                ('interventions', models.JSONField(blank=True, default=list, help_text='List of planned interventions')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('ON_HOLD', 'On Hold'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='care_plans', to=settings.AUTH_USER_MODEL)),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='care_plans', to='medos.encounter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_plans', to='medos.patient')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient', 'status'], name='medos_carep_patient_b3a7de_idx'), models.Index(fields=['-created_at'], name='medos_carep_created_ea6170_idx')],
            },
        ),
        migrations.CreateModel(
            name='PatientDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('LAB_REPORT', 'Lab Report'), ('IMAGING_REPORT', 'Imaging Report'), ('PRESCRIPTION', 'Prescription'), ('CONSENT_FORM', 'Consent Form'), ('DISCHARGE_SUMMARY', 'Discharge Summary'), ('REFERRAL', 'Referral Letter'), ('VACCINATION', 'Vaccination Record'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('file_url', models.URLField(help_text='URL or path to uploaded document')),
                ('notes', models.TextField(blank=True, default='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='medos.encounter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='medos.patient')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['patient', 'document_type'], name='medos_patie_patient_c17cd1_idx'), models.Index(fields=['encounter'], name='medos_patie_encount_040e9b_idx'), models.Index(fields=['-uploaded_at'], name='medos_patie_uploade_3219d9_idx')],
            },
        ),
    ]
