# Generated by Django 6.0.6 on 2026-06-10 13:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medos', '0007_billing_dashboard_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='aadhaar_number',
            field=models.CharField(blank=True, help_text='Aadhaar number (12 digits)', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='address_line1',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='patient',
            name='address_line2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='patient',
            name='country',
            field=models.CharField(blank=True, default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contact_alternate_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contact_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='identification_number',
            field=models.CharField(blank=True, default='', help_text='Government ID number', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='identification_type',
            field=models.CharField(blank=True, choices=[('AADHAAR', 'Aadhaar'), ('PAN', 'PAN Card'), ('VOTER_ID', 'Voter ID'), ('PASSPORT', 'Passport'), ('DRIVING_LICENSE', 'Driving License'), ('OTHER', 'Other')], default='', help_text='Type of government ID', max_length=30),
        ),
        migrations.AddField(
            model_name='patient',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('DIVORCED', 'Divorced'), ('WIDOWED', 'Widowed'), ('OTHER', 'Other')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='nationality',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='pan_number',
            field=models.CharField(blank=True, help_text='PAN card number', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='registration_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('COMPLETED', 'Completed')], default='DRAFT', help_text='Wizard state: Draft until all steps completed', max_length=20),
        ),
        migrations.CreateModel(
            name='PatientInsurance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_name', models.CharField(help_text='Insurance provider / TPA name', max_length=200)),
                ('policy_number', models.CharField(help_text='Policy number', max_length=100)),
                ('valid_upto', models.DateField(blank=True, help_text='Policy valid until date', null=True)),
                ('coverage_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Coverage amount', max_digits=12, null=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary insurance policy')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_policies', to='medos.patient')),
            ],
            options={
                'ordering': ['-is_primary', '-created_at'],
                'indexes': [models.Index(fields=['patient', 'provider_name'], name='medos_patie_patient_23edcf_idx')],
            },
        ),
    ]
