# Generated by Django 6.0.6 on 2026-06-10 13:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medos', '0008_patient_aadhaar_number_patient_address_line1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ICUWard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Ward name, e.g. Cardiac ICU', max_length=200, unique=True)),
                ('total_beds', models.IntegerField(default=0, help_text='Total number of beds in this ward')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='vitals',
            name='is_live',
            field=models.BooleanField(default=False, help_text='True for real-time TeleICU streaming vitals, False for manually recorded'),
        ),
        migrations.CreateModel(
            name='ICUBed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bed_number', models.CharField(help_text='Bed identifier, e.g. Bed-01', max_length=20)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('MAINTENANCE', 'Maintenance')], default='AVAILABLE', max_length=20)),
                ('camera_feed_url', models.URLField(blank=True, default='', help_text='RTSP / WebRTC URL for live camera feed')),
                ('device_ip', models.CharField(blank=True, default='', help_text='IP address of bedside monitor / hub', max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='medos.icuward')),
            ],
            options={
                'ordering': ['ward__name', 'bed_number'],
            },
        ),
        migrations.CreateModel(
            name='SystemActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('VITALS_UPDATE', 'Vitals Update'), ('VENT_SETTINGS', 'Vent Settings'), ('LAB_REPORT', 'Lab Report'), ('MEDICATION', 'Medication'), ('ALERT', 'Alert'), ('CONSULT', 'Consultation'), ('ADMISSION', 'Admission'), ('DISCHARGE', 'Discharge'), ('SYSTEM', 'System Event')], default='SYSTEM', max_length=30)),
                ('description', models.TextField(blank=True, default='')),
                ('author_name', models.CharField(blank=True, default='System', help_text='Display name of the person/system that triggered the event', max_length=200)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional structured data about the event')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='medos.encounter')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='medos.patient')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TeleConsultSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('specialty', models.CharField(blank=True, default='', help_text='Specialty requested, e.g. Cardiology', max_length=100)),
                ('call_type', models.CharField(choices=[('VIDEO', 'Video Call'), ('AUDIO', 'Audio Call')], default='VIDEO', max_length=10)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('meeting_link', models.URLField(blank=True, default='', help_text='WebRTC / Zoom / Jitsi meeting link')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tele_consults', to=settings.AUTH_USER_MODEL)),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tele_consults', to='medos.encounter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tele_consults', to='medos.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeleICUSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('acuity_status', models.CharField(choices=[('CRITICAL', 'Critical'), ('UNSTABLE', 'Unstable'), ('STABLE', 'Stable')], default='STABLE', max_length=20)),
                ('support_type', models.CharField(blank=True, choices=[('VENTILATOR', 'On Ventilator'), ('OXYGEN', 'On Oxygen'), ('ROOM_AIR', 'Room Air'), ('BIPAP', 'On BiPAP'), ('CPAP', 'On CPAP')], default='', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('admitted_at', models.DateTimeField(auto_now_add=True)),
                ('discharged_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='medos.icubed')),
                ('encounter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teleicu_session', to='medos.encounter')),
            ],
            options={
                'ordering': ['-admitted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='icubed',
            index=models.Index(fields=['ward', 'status'], name='medos_icube_ward_id_1b4a0c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='icubed',
            unique_together={('ward', 'bed_number')},
        ),
        migrations.AddIndex(
            model_name='systemactivitylog',
            index=models.Index(fields=['patient', '-timestamp'], name='medos_syste_patient_8ba6d9_idx'),
        ),
        migrations.AddIndex(
            model_name='systemactivitylog',
            index=models.Index(fields=['event_type'], name='medos_syste_event_t_ae0347_idx'),
        ),
        migrations.AddIndex(
            model_name='systemactivitylog',
            index=models.Index(fields=['-timestamp'], name='medos_syste_timesta_ea2a89_idx'),
        ),
        migrations.AddIndex(
            model_name='teleconsultsession',
            index=models.Index(fields=['status', 'specialty'], name='medos_telec_status_b9704b_idx'),
        ),
        migrations.AddIndex(
            model_name='teleconsultsession',
            index=models.Index(fields=['patient', '-created_at'], name='medos_telec_patient_91a236_idx'),
        ),
        migrations.AddIndex(
            model_name='teleconsultsession',
            index=models.Index(fields=['doctor', '-created_at'], name='medos_telec_doctor__25b00b_idx'),
        ),
        migrations.AddIndex(
            model_name='teleicusession',
            index=models.Index(fields=['is_active', 'acuity_status'], name='medos_telei_is_acti_c7c62e_idx'),
        ),
        migrations.AddIndex(
            model_name='teleicusession',
            index=models.Index(fields=['bed'], name='medos_telei_bed_id_2c758f_idx'),
        ),
    ]
