# Generated by Django 6.0.6 on 2026-06-10 13:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medos', '0009_icuward_vitals_is_live_icubed_systemactivitylog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabInventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_name', models.CharField(help_text='e.g. "EDTA Tubes", "Reagent Kit CBC"', max_length=300)),
                ('item_type', models.CharField(choices=[('REAGENT', 'Reagent'), ('CONSUMABLE', 'Consumable'), ('EQUIPMENT', 'Equipment')], default='REAGENT', max_length=20)),
                ('current_stock', models.IntegerField(default=0, help_text='Current quantity in stock')),
                ('min_stock_threshold', models.IntegerField(default=0, help_text='Alert when stock falls below this')),
                ('unit', models.CharField(blank=True, default='', help_text='e.g. boxes, vials, units', max_length=50)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('batch_number', models.CharField(blank=True, default='', max_length=100)),
                ('location', models.CharField(blank=True, default='', help_text='Storage location (e.g. "Fridge 3, Shelf B")', max_length=200)),
                ('last_restocked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Lab inventory',
                'ordering': ['item_name'],
                'indexes': [models.Index(fields=['item_type'], name='medos_labin_item_ty_7597e3_idx'), models.Index(fields=['current_stock'], name='medos_labin_current_daf31f_idx')],
            },
        ),
        migrations.CreateModel(
            name='TestPanel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Full name, e.g. "Complete Blood Count (CBC)"', max_length=300)),
                ('short_name', models.CharField(blank=True, default='', help_text='Abbreviation, e.g. CBC', max_length=50)),
                ('category', models.CharField(choices=[('HEMATOLOGY', 'Hematology'), ('BIOCHEMISTRY', 'Biochemistry'), ('MICROBIOLOGY', 'Microbiology'), ('PATHOLOGY', 'Pathology'), ('IMMUNOLOGY', 'Immunology'), ('SEROLOGY', 'Serology'), ('TOXICOLOGY', 'Toxicology'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('description', models.TextField(blank=True, default='', help_text='What the test measures')),
                ('standard_tat_hours', models.IntegerField(default=24, help_text='Standard turnaround time in hours')),
                ('sample_types', models.JSONField(blank=True, default=list, help_text='Accepted sample types, e.g. ["Blood (EDTA)", "Serum"]')),
                ('method', models.CharField(blank=True, default='', help_text='Analysis method, e.g. "Automated (Sysmex XN-1000)"', max_length=200)),
                ('lab_location', models.CharField(blank=True, default='', help_text='e.g. "Main Laboratory", "Microbiology Wing"', max_length=200)),
                ('is_panel', models.BooleanField(default=False, help_text='True if this contains multiple sub-tests / parameters')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Standard price', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['category'], name='medos_testp_categor_a0276c_idx'), models.Index(fields=['short_name'], name='medos_testp_short_n_67fa93_idx')],
            },
        ),
        migrations.CreateModel(
            name='LabOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lab_id', models.CharField(blank=True, editable=False, help_text='Auto-generated, e.g. LAB-20260610-0001', max_length=30, unique=True)),
                ('department', models.CharField(blank=True, default='', help_text='Department requesting the test, e.g. Cardiology', max_length=100)),
                ('sample_type', models.CharField(blank=True, choices=[('BLOOD_EDTA', 'Blood (EDTA)'), ('BLOOD_CLOT', 'Blood (Clot)'), ('SERUM', 'Serum'), ('PLASMA', 'Plasma'), ('URINE', 'Urine'), ('STOOL', 'Stool'), ('CSF', 'CSF'), ('SWAB', 'Swab'), ('SPUTUM', 'Sputum'), ('TISSUE', 'Tissue'), ('OTHER', 'Other')], default='', max_length=20)),
                ('priority', models.CharField(choices=[('ROUTINE', 'Routine'), ('URGENT', 'Urgent'), ('STAT', 'STAT')], default='ROUTINE', max_length=20)),
                ('status', models.CharField(choices=[('ORDERED', 'Ordered'), ('SAMPLE_COLLECTED', 'Sample Collected'), ('RECEIVED_IN_LAB', 'Received in Lab'), ('IN_PROGRESS', 'In Progress'), ('UNDER_REVIEW', 'Under Review'), ('COMPLETED', 'Completed'), ('CRITICAL', 'Critical'), ('CANCELLED', 'Cancelled')], default='ORDERED', max_length=20)),
                ('barcode', models.CharField(blank=True, help_text='Accession number, e.g. BC602260001', max_length=30, null=True, unique=True)),
                ('visit_type', models.CharField(blank=True, choices=[('OPD', 'OPD'), ('IPD', 'IPD'), ('ER', 'Emergency')], default='', max_length=10)),
                ('bed_unit', models.CharField(blank=True, default='', help_text='Bed/ward for IPD patients, e.g. ICU-05', max_length=50)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('sample_collected_at', models.DateTimeField(blank=True, null=True)),
                ('received_in_lab_at', models.DateTimeField(blank=True, null=True)),
                ('analysis_completed_at', models.DateTimeField(blank=True, null=True)),
                ('reported_at', models.DateTimeField(blank=True, null=True)),
                ('tat_deadline', models.DateTimeField(blank=True, help_text='Auto-calculated from test TAT SLA', null=True)),
                ('comments', models.TextField(blank=True, default='', help_text='Pathologist comments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_orders', to='medos.encounter')),
                ('ordered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_orders_placed', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to='medos.patient')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_reviews', to=settings.AUTH_USER_MODEL)),
                ('test_panel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='medos.testpanel')),
            ],
            options={
                'ordering': ['-ordered_at'],
            },
        ),
        migrations.CreateModel(
            name='TestParameter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group', models.CharField(blank=True, default='', help_text='Group heading, e.g. "Differential Count"', max_length=100)),
                ('name', models.CharField(help_text='Parameter name, e.g. "Hemoglobin (Hb)"', max_length=200)),
                ('unit', models.CharField(blank=True, default='', help_text='Unit of measurement, e.g. "g/dL"', max_length=50)),
                ('ref_range_low', models.DecimalField(blank=True, decimal_places=2, help_text='Lower bound of normal range', max_digits=10, null=True)),
                ('ref_range_high', models.DecimalField(blank=True, decimal_places=2, help_text='Upper bound of normal range', max_digits=10, null=True)),
                ('critical_low', models.DecimalField(blank=True, decimal_places=2, help_text='Critical low threshold', max_digits=10, null=True)),
                ('critical_high', models.DecimalField(blank=True, decimal_places=2, help_text='Critical high threshold', max_digits=10, null=True)),
                ('display_order', models.IntegerField(default=0, help_text='Sorting order within the group')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='medos.testpanel')),
            ],
            options={
                'ordering': ['panel', 'group', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LabParameterResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result_value', models.CharField(blank=True, default='', help_text='Stored as string to handle qualitative results too', max_length=200)),
                ('result_numeric', models.DecimalField(blank=True, decimal_places=3, help_text='Numeric value used for trend calculations', max_digits=12, null=True)),
                ('status', models.CharField(choices=[('NORMAL', 'Normal'), ('LOW', 'Low'), ('HIGH', 'High'), ('CRITICAL', 'Critical'), ('PENDING', 'Pending')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_parameter_entries', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_results', to='medos.laborder')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='medos.testparameter')),
            ],
            options={
                'ordering': ['order', 'parameter__group', 'parameter__display_order'],
            },
        ),
        migrations.CreateModel(
            name='LabDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('PDF_REPORT', 'PDF Report'), ('IMAGE', 'Image'), ('RAW_DATA', 'Raw Data'), ('OTHER', 'Other')], default='PDF_REPORT', max_length=20)),
                ('file_url', models.URLField(help_text='URL or path to uploaded document')),
                ('filename', models.CharField(blank=True, default='', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='medos.laborder')),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['order', 'document_type'], name='medos_labdo_order_i_3b08ef_idx')],
            },
        ),
        migrations.CreateModel(
            name='LabAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_message', models.CharField(help_text='e.g. "CBC - Low Hemoglobin"', max_length=500)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('WARNING', 'Warning')], default='CRITICAL', max_length=20)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_alerts', to='medos.patient')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='medos.laborder')),
                ('parameter_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='medos.labparameterresult')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order', 'is_acknowledged'], name='medos_labal_order_i_27e0da_idx'), models.Index(fields=['patient', '-created_at'], name='medos_labal_patient_d4f570_idx'), models.Index(fields=['severity'], name='medos_labal_severit_4006f6_idx')],
            },
        ),
        migrations.CreateModel(
            name='QCEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(help_text='e.g. "Sample Received", "Review Approved"', max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('instrument_id', models.CharField(blank=True, default='', help_text='Analyzer / machine that processed the sample', max_length=100)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qc_entries', to='medos.laborder')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'QC entries',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['order', '-timestamp'], name='medos_qcent_order_i_a17e4e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='laborder',
            index=models.Index(fields=['lab_id'], name='medos_labor_lab_id_9eca7d_idx'),
        ),
        migrations.AddIndex(
            model_name='laborder',
            index=models.Index(fields=['patient', '-ordered_at'], name='medos_labor_patient_98a54e_idx'),
        ),
        migrations.AddIndex(
            model_name='laborder',
            index=models.Index(fields=['status'], name='medos_labor_status_0fb52a_idx'),
        ),
        migrations.AddIndex(
            model_name='laborder',
            index=models.Index(fields=['barcode'], name='medos_labor_barcode_2a3323_idx'),
        ),
        migrations.AddIndex(
            model_name='laborder',
            index=models.Index(fields=['encounter'], name='medos_labor_encount_d479ac_idx'),
        ),
        migrations.AddIndex(
            model_name='testparameter',
            index=models.Index(fields=['panel', 'group'], name='medos_testp_panel_i_62d886_idx'),
        ),
        migrations.AddIndex(
            model_name='testparameter',
            index=models.Index(fields=['name'], name='medos_testp_name_a3a23a_idx'),
        ),
        migrations.AddIndex(
            model_name='labparameterresult',
            index=models.Index(fields=['order', 'parameter'], name='medos_labpa_order_i_9bb046_idx'),
        ),
        migrations.AddIndex(
            model_name='labparameterresult',
            index=models.Index(fields=['status'], name='medos_labpa_status_d61340_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='labparameterresult',
            unique_together={('order', 'parameter')},
        ),
    ]
