# Generated by Django 6.0.6 on 2026-06-10 14:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medos', '0010_labinventory_testpanel_laborder_testparameter_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g., "Daily Revenue Report", "Weekly Clinical Summary"', max_length=200)),
                ('category', models.CharField(choices=[('BILLING', 'Billing'), ('EMR', 'EMR'), ('PHARMACY', 'Pharmacy'), ('LABORATORY', 'Laboratory'), ('OPERATIONS', 'Operations')], max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('supported_formats', models.JSONField(blank=True, default=list, help_text='e.g. ["pdf", "excel", "csv"]')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('insight_type', models.CharField(choices=[('REVENUE', 'Revenue'), ('OCCUPANCY', 'Occupancy'), ('LAB_BACKLOG', 'Lab Backlog'), ('READMISSION_RISK', 'Readmission Risk'), ('BILLING_ANOMALY', 'Billing Anomaly'), ('TAT_BREACH', 'TAT Breach'), ('UTILIZATION', 'Utilization')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='INFO', max_length=10)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['insight_type'], name='medos_aiins_insight_dacbb8_idx'), models.Index(fields=['severity'], name='medos_aiins_severit_685bf9_idx'), models.Index(fields=['-generated_at'], name='medos_aiins_generat_617e2a_idx')],
            },
        ),
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('generated_on', models.DateTimeField(auto_now_add=True)),
                ('parameters_used', models.JSONField(blank=True, default=dict, help_text='Date range, filters applied')),
                ('format_type', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel'), ('CSV', 'CSV')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('file_url', models.URLField(blank=True, default='', help_text='Link to S3/Storage')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('report_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to='medos.reportdefinition')),
            ],
            options={
                'ordering': ['-generated_on'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], max_length=20)),
                ('schedule_time', models.TimeField(help_text='e.g. 09:00:00')),
                ('recipients', models.JSONField(blank=True, default=list, help_text='List of email addresses')),
                ('is_active', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_reports', to='medos.reportdefinition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedDashboardView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('view_name', models.CharField(max_length=200)),
                ('filters', models.JSONField(blank=True, default=dict, help_text='Saved state of date range, locations, departments, etc.')),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_dashboard_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_pinned', '-updated_at'],
                'unique_together': {('user', 'view_name')},
            },
        ),
    ]
