# Generated by Django 6.0.6 on 2026-06-10

import uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medos', '0011_reports_analytics_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Machine name, e.g. emr, billing, pharmacy', max_length=100, unique=True)),
                ('label', models.CharField(help_text='Human-readable name, e.g. EMR, Patient Registration', max_length=100)),
                ('status', models.CharField(choices=[('Operational', 'Operational'), ('Degraded', 'Degraded'), ('Offline', 'Offline')], default='Operational', max_length=20)),
                ('is_critical', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('backup_type', models.CharField(choices=[('MANUAL', 'Manual'), ('SCHEDULED', 'Scheduled')], max_length=20)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='IN_PROGRESS', max_length=20)),
                ('file_url', models.URLField(blank=True, default='')),
                ('file_size_mb', models.FloatField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(help_text='Short code, e.g. CARD, ORTH', max_length=20, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('head_of_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeviceIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('device_type', models.CharField(help_text='e.g. biometric_scanner, lab_machine, bedside_monitor', max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('api_endpoint', models.URLField(blank=True, default='')),
                ('auth_type', models.CharField(choices=[('api_key', 'API Key'), ('basic', 'Basic Auth'), ('oauth', 'OAuth 2.0'), ('none', 'No Auth')], default='none', max_length=20)),
                ('credentials', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LicenseInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('edition', models.CharField(choices=[('Community', 'Community'), ('Professional', 'Professional'), ('Enterprise', 'Enterprise')], default='Enterprise', max_length=50)),
                ('license_key', models.CharField(blank=True, default='', max_length=200)),
                ('valid_from', models.DateField()),
                ('valid_till', models.DateField()),
                ('registered_modules', models.IntegerField(default=0)),
                ('total_modules', models.IntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('user_limit', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'license info',
                'ordering': ['-valid_till'],
            },
        ),
        migrations.CreateModel(
            name='MasterDataEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(db_index=True, help_text='e.g. specialty, encounter_type, room_type, visit_type', max_length=100)),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Optional extra data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'master data entries',
                'ordering': ['category', 'display_order', 'key'],
                'unique_together': {('category', 'key')},
            },
        ),
        migrations.CreateModel(
            name='SecurityPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('policy_type', models.CharField(choices=[('password_policy', 'Password Policy'), ('two_factor', 'Two-Factor Authentication'), ('session', 'Session Timeout'), ('ip_whitelist', 'IP Whitelist'), ('login_attempts', 'Login Attempts Limit')], max_length=50, unique=True)),
                ('settings', models.JSONField(default=dict, help_text='Policy-specific settings as JSON')),
                ('is_enforced', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['policy_type'],
            },
        ),
        migrations.CreateModel(
            name='StorageMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('storage_used_gb', models.FloatField(help_text='Used storage in GB')),
                ('storage_total_gb', models.FloatField(help_text='Total capacity in GB')),
                ('database_status', models.CharField(default='Healthy', help_text='e.g. Healthy, Degraded, Critical', max_length=50)),
                ('last_backup', models.DateTimeField(blank=True, null=True)),
                ('next_backup', models.DateTimeField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'storage metrics',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Info'), ('success', 'Success')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=200)),
                ('value', models.JSONField(help_text='Stored as JSON; cast to value_type on read')),
                ('value_type', models.CharField(choices=[('string', 'String'), ('number', 'Number'), ('boolean', 'Boolean'), ('json', 'JSON'), ('email', 'Email'), ('url', 'URL')], default='string', max_length=20)),
                ('category', models.CharField(choices=[('general', 'General'), ('hospital', 'Hospital Info'), ('email', 'Email / SMTP'), ('security', 'Security'), ('billing', 'Billing'), ('appointment', 'Appointment'), ('notification', 'Notification')], default='general', max_length=100)),
                ('is_encrypted', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'key'],
            },
        ),
        migrations.CreateModel(
            name='UserLoginActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('login_timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('was_successful', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-login_timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='userloginactivity',
            index=models.Index(fields=['-login_timestamp'], name='medos_userl_login_t_7f20c8_idx'),
        ),
        migrations.AddIndex(
            model_name='userloginactivity',
            index=models.Index(fields=['user', '-login_timestamp'], name='medos_userl_user_id_2884c2_idx'),
        ),
        migrations.CreateModel(
            name='WorkflowDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('module', models.CharField(help_text='Target module, e.g. billing, pharmacy, lab', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('initial_state', models.CharField(max_length=100)),
                ('states', models.JSONField(help_text='List of state objects: [{"name": "...", "label": "..."}]')),
                ('transitions', models.JSONField(help_text='List of transition objects: [{"from": "...", "to": "...", "action": "..."}]')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['module', 'name'],
                'unique_together': {('module', 'name')},
            },
        ),
    ]
