# Generated by Django 6.0.6 on 2026-06-10 15:31

from datetime import date, timedelta

from django.db import migrations


def seed_admin_modules(apps, schema_editor):
    """Seed default system modules with operational status."""
    AdminModule = apps.get_model('medos', 'AdminModule')
    modules = [
        ('emr', 'EMR', True),
        ('patient_registration', 'Patient Registration', True),
        ('billing', 'Billing', True),
        ('pharmacy', 'Pharmacy', True),
        ('laboratory', 'Laboratory', True),
        ('teleicu', 'TeleICU', True),
        ('ai_services', 'AI Services', False),
    ]
    for name, label, critical in modules:
        AdminModule.objects.get_or_create(
            name=name,
            defaults={
                'label': label,
                'status': 'Operational',
                'is_critical': critical,
            },
        )


def seed_security_policies(apps, schema_editor):
    """Seed default security policies."""
    SecurityPolicy = apps.get_model('medos', 'SecurityPolicy')
    defaults = [
        {
            'policy_type': 'password_policy',
            'settings': {
                'strength': 'Strong',
                'min_length': 8,
                'require_uppercase': True,
                'require_lowercase': True,
                'require_digit': True,
                'require_special': True,
                'expiry_days': 90,
            },
            'description': 'Password complexity and expiry rules.',
        },
        {
            'policy_type': 'two_factor',
            'settings': {
                'enforcement': 'Optional',
                'methods': ['authenticator_app', 'sms', 'email'],
            },
            'description': 'Two-factor authentication settings.',
        },
        {
            'policy_type': 'session',
            'settings': {
                'timeout_minutes': 30,
                'max_concurrent_sessions': 5,
                'remember_me_days': 14,
            },
            'description': 'Session timeout and concurrency rules.',
        },
        {
            'policy_type': 'ip_whitelist',
            'settings': {
                'enabled': False,
                'allowed_ips': [],
            },
            'description': 'IP whitelist for admin panel access.',
        },
        {
            'policy_type': 'login_attempts',
            'settings': {
                'max_attempts': 5,
                'lockout_minutes': 15,
            },
            'description': 'Login attempt limits and lockout rules.',
        },
    ]
    for policy in defaults:
        SecurityPolicy.objects.get_or_create(
            policy_type=policy['policy_type'],
            defaults=policy,
        )


def seed_system_settings(apps, schema_editor):
    """Seed default system settings."""
    SystemSetting = apps.get_model('medos', 'SystemSetting')
    defaults = [
        {
            'key': 'hospital_name',
            'label': 'Hospital Name',
            'value': 'MedOS Hospital',
            'value_type': 'string',
            'category': 'hospital',
        },
        {
            'key': 'hospital_logo_url',
            'label': 'Hospital Logo URL',
            'value': '',
            'value_type': 'url',
            'category': 'hospital',
        },
        {
            'key': 'hospital_contact_email',
            'label': 'Hospital Contact Email',
            'value': 'admin@medoshospital.com',
            'value_type': 'email',
            'category': 'hospital',
        },
        {
            'key': 'hospital_contact_phone',
            'label': 'Hospital Contact Phone',
            'value': '+91-1800-123-4567',
            'value_type': 'string',
            'category': 'hospital',
        },
        {
            'key': 'hospital_address',
            'label': 'Hospital Address',
            'value': '123 Healthcare Ave, Medical District',
            'value_type': 'string',
            'category': 'hospital',
        },
        {
            'key': 'smtp_host',
            'label': 'SMTP Host',
            'value': 'smtp.gmail.com',
            'value_type': 'string',
            'category': 'email',
        },
        {
            'key': 'smtp_port',
            'label': 'SMTP Port',
            'value': 587,
            'value_type': 'number',
            'category': 'email',
        },
        {
            'key': 'smtp_use_tls',
            'label': 'SMTP Use TLS',
            'value': True,
            'value_type': 'boolean',
            'category': 'email',
        },
        {
            'key': 'default_appointment_duration',
            'label': 'Default Appointment Duration (min)',
            'value': 15,
            'value_type': 'number',
            'category': 'appointment',
        },
        {
            'key': 'enable_teleicu',
            'label': 'Enable TeleICU Module',
            'value': True,
            'value_type': 'boolean',
            'category': 'general',
        },
        {
            'key': 'enable_care_scribe',
            'label': 'Enable Care Scribe AI',
            'value': True,
            'value_type': 'boolean',
            'category': 'general',
        },
        {
            'key': 'currency_symbol',
            'label': 'Currency Symbol',
            'value': '\u20b9',
            'value_type': 'string',
            'category': 'billing',
        },
        {
            'key': 'tax_percent_default',
            'label': 'Default Tax Percentage',
            'value': 18,
            'value_type': 'number',
            'category': 'billing',
        },
        {
            'key': 'enable_email_notifications',
            'label': 'Enable Email Notifications',
            'value': True,
            'value_type': 'boolean',
            'category': 'notification',
        },
        {
            'key': 'enable_sms_notifications',
            'label': 'Enable SMS Notifications',
            'value': False,
            'value_type': 'boolean',
            'category': 'notification',
        },
    ]
    for s in defaults:
        SystemSetting.objects.get_or_create(
            key=s['key'],
            defaults=s,
        )


def seed_license_info(apps, schema_editor):
    """Seed default license information."""
    LicenseInfo = apps.get_model('medos', 'LicenseInfo')
    LicenseInfo.objects.get_or_create(
        edition='Enterprise',
        defaults={
            'license_key': 'MEDOS-ENT-2026-00001',
            'valid_from': date(2026, 1, 1),
            'valid_till': date(2027, 1, 1),
            'registered_modules': 8,
            'total_modules': 10,
            'active_users': 0,  # Will be updated at runtime
            'user_limit': 500,
            'is_active': True,
        },
    )


def seed_storage_metrics(apps, schema_editor):
    """Seed initial storage metrics."""
    StorageMetrics = apps.get_model('medos', 'StorageMetrics')
    StorageMetrics.objects.create(
        storage_used_gb=128.5,
        storage_total_gb=500.0,
        database_status='Healthy',
        last_backup=None,
        next_backup=None,
    )


def seed_master_data(apps, schema_editor):
    """Seed common lookup table entries."""
    MasterDataEntry = apps.get_model('medos', 'MasterDataEntry')
    entries = [
        # Specialties
        {'category': 'specialty', 'key': 'cardiology', 'value': 'Cardiology', 'display_order': 1},
        {'category': 'specialty', 'key': 'orthopedics', 'value': 'Orthopedics', 'display_order': 2},
        {'category': 'specialty', 'key': 'neurology', 'value': 'Neurology', 'display_order': 3},
        {'category': 'specialty', 'key': 'pediatrics', 'value': 'Pediatrics', 'display_order': 4},
        {'category': 'specialty', 'key': 'gynecology', 'value': 'Gynecology', 'display_order': 5},
        {'category': 'specialty', 'key': 'dermatology', 'value': 'Dermatology', 'display_order': 6},
        {'category': 'specialty', 'key': 'ophthalmology', 'value': 'Ophthalmology', 'display_order': 7},
        {'category': 'specialty', 'key': 'ent', 'value': 'ENT', 'display_order': 8},
        {'category': 'specialty', 'key': 'psychiatry', 'value': 'Psychiatry', 'display_order': 9},
        {'category': 'specialty', 'key': 'general_medicine', 'value': 'General Medicine', 'display_order': 10},
        # Encounter Types
        {'category': 'encounter_type', 'key': 'opd', 'value': 'OPD Consultation', 'display_order': 1},
        {'category': 'encounter_type', 'key': 'ipd', 'value': 'IPD Admission', 'display_order': 2},
        {'category': 'encounter_type', 'key': 'emergency', 'value': 'Emergency', 'display_order': 3},
        {'category': 'encounter_type', 'key': 'teleconsultation', 'value': 'Teleconsultation', 'display_order': 4},
        {'category': 'encounter_type', 'key': 'icu', 'value': 'ICU', 'display_order': 5},
        {'category': 'encounter_type', 'key': 'daycare', 'value': 'Day Care', 'display_order': 6},
        # Room Types
        {'category': 'room_type', 'key': 'general_ward', 'value': 'General Ward', 'display_order': 1},
        {'category': 'room_type', 'key': 'semi_private', 'value': 'Semi-Private', 'display_order': 2},
        {'category': 'room_type', 'key': 'private', 'value': 'Private Room', 'display_order': 3},
        {'category': 'room_type', 'key': 'deluxe', 'value': 'Deluxe Suite', 'display_order': 4},
        {'category': 'room_type', 'key': 'icu', 'value': 'ICU', 'display_order': 5},
        # Visit Types
        {'category': 'visit_type', 'key': 'new', 'value': 'New Patient', 'display_order': 1},
        {'category': 'visit_type', 'key': 'follow_up', 'value': 'Follow-up', 'display_order': 2},
        {'category': 'visit_type', 'key': 'review', 'value': 'Review', 'display_order': 3},
        {'category': 'visit_type', 'key': 'emergency', 'value': 'Emergency', 'display_order': 4},
    ]
    for entry in entries:
        MasterDataEntry.objects.get_or_create(
            category=entry['category'],
            key=entry['key'],
            defaults=entry,
        )


def reverse_func(apps, schema_editor):
    """Reverse the seed data."""
    AdminModule = apps.get_model('medos', 'AdminModule')
    SecurityPolicy = apps.get_model('medos', 'SecurityPolicy')
    SystemSetting = apps.get_model('medos', 'SystemSetting')
    LicenseInfo = apps.get_model('medos', 'LicenseInfo')
    StorageMetrics = apps.get_model('medos', 'StorageMetrics')
    MasterDataEntry = apps.get_model('medos', 'MasterDataEntry')

    AdminModule.objects.all().delete()
    SecurityPolicy.objects.all().delete()
    SystemSetting.objects.all().delete()
    LicenseInfo.objects.all().delete()
    StorageMetrics.objects.all().delete()
    MasterDataEntry.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('medos', '0012_admin_panel_models'),
    ]

    operations = [
        migrations.RunPython(seed_admin_modules, reverse_code=reverse_func),
        migrations.RunPython(seed_security_policies, reverse_code=reverse_func),
        migrations.RunPython(seed_system_settings, reverse_code=reverse_func),
        migrations.RunPython(seed_license_info, reverse_code=reverse_func),
        migrations.RunPython(seed_storage_metrics, reverse_code=reverse_func),
        migrations.RunPython(seed_master_data, reverse_code=reverse_func),
    ]
