# Generated by Django 6.0.6 on 2026-06-10 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medos', '0013_seed_admin_data'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userloginactivity',
            new_name='medos_userl_login_t_66acb2_idx',
            old_name='medos_userl_login_t_7f20c8_idx',
        ),
        migrations.RenameIndex(
            model_name='userloginactivity',
            new_name='medos_userl_user_id_b70425_idx',
            old_name='medos_userl_user_id_2884c2_idx',
        ),
    ]
