# Generated by Django 6.0.6 on 2026-06-10 17:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medos', '0014_rename_medos_userl_login_t_7f20c8_idx_medos_userl_login_t_66acb2_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tax_inclusive', models.BooleanField(default=False)),
                ('auto_invoice_generation', models.BooleanField(default=False)),
                ('allow_partial_payments', models.BooleanField(default=False)),
                ('require_discount_approval', models.BooleanField(default=True)),
                ('default_payment_terms_days', models.IntegerField(default=30)),
                ('default_tax_rate', models.FloatField(default=0.0)),
                ('acceptable_payment_methods', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name_plural': 'billing settings',
            },
        ),
        migrations.CreateModel(
            name='DataPolicySettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinical_retention_years', models.IntegerField(default=10)),
                ('financial_retention_years', models.IntegerField(default=7)),
                ('auto_archive_inactive_patients', models.BooleanField(default=False)),
                ('anonymize_research_data', models.BooleanField(default=False)),
                ('enable_daily_snapshots', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'data policy settings',
            },
        ),
        migrations.CreateModel(
            name='HospitalProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('address', models.TextField(blank=True, default='')),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=50)),
                ('registration_number', models.CharField(blank=True, default='', max_length=100)),
                ('logo_url', models.URLField(blank=True, default='')),
                ('facilities', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name_plural': 'hospital profiles',
            },
        ),
        migrations.CreateModel(
            name='IntegrationSetting',
            fields=[
                ('id', models.CharField(choices=[('pacs', 'PACS'), ('lis', 'LIS'), ('ndhm', 'NDHM'), ('tpa', 'TPA'), ('payment', 'Payment Gateway')], max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('connected', models.BooleanField(default=False)),
                ('client_id', models.CharField(blank=True, default='', max_length=500)),
                ('client_secret', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LaboratorySettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auto_approve_normal_results', models.BooleanField(default=False)),
                ('critical_value_sms_alerts', models.BooleanField(default=True)),
                ('enable_external_portal', models.BooleanField(default=False)),
                ('default_turnaround_time_hours', models.IntegerField(default=24)),
                ('qc_check_frequency_per_week', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'laboratory settings',
            },
        ),
        migrations.CreateModel(
            name='LocalizationSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_language', models.CharField(default='English', max_length=50)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=100)),
                ('default_currency', models.CharField(default='INR', max_length=10)),
                ('date_format', models.CharField(default='DD/MM/YYYY', max_length=20)),
                ('time_format', models.CharField(default='12-hour', max_length=20)),
                ('multi_currency_support', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'localization settings',
            },
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sms_gateway_api_key', models.CharField(blank=True, default='', max_length=500)),
                ('email_smtp_server', models.CharField(blank=True, default='', max_length=255)),
                ('email_smtp_port', models.IntegerField(default=587)),
                ('email_username', models.CharField(blank=True, default='', max_length=255)),
                ('email_password', models.CharField(blank=True, default='', max_length=500)),
                ('send_sms_on_booking', models.BooleanField(default=False)),
                ('send_email_on_discharge', models.BooleanField(default=False)),
                ('send_sms_for_critical_labs', models.BooleanField(default=False)),
                ('send_email_for_daily_reports', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'notification settings',
            },
        ),
        migrations.CreateModel(
            name='PharmacySettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auto_reorder_alerts', models.BooleanField(default=True)),
                ('strict_expiry_enforcement', models.BooleanField(default=True)),
                ('require_prescription_for_dispense', models.BooleanField(default=False)),
                ('default_expiry_warning_days', models.IntegerField(default=60)),
                ('minimum_stock_threshold_percent', models.FloatField(default=20.0)),
            ],
            options={
                'verbose_name_plural': 'pharmacy settings',
            },
        ),
        migrations.CreateModel(
            name='TeleICUSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auto_record_consults', models.BooleanField(default=False)),
                ('continuous_monitoring_sync', models.BooleanField(default=False)),
                ('alert_escalation_to_oncall', models.BooleanField(default=True)),
                ('vitals_refresh_rate_seconds', models.IntegerField(default=5)),
                ('high_heart_rate_threshold', models.IntegerField(default=120)),
                ('low_spo2_threshold', models.IntegerField(default=90)),
                ('default_camera_quality', models.CharField(choices=[('720p', '720p'), ('1080p', '1080p'), ('4K', '4K')], default='720p', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'teleicu settings',
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('invoices', 'Invoices'), ('prescriptions', 'Prescriptions'), ('discharge_summaries', 'Discharge Summaries'), ('lab_reports', 'Lab Reports')], max_length=50)),
                ('content', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('secret', models.CharField(blank=True, default='', max_length=500)),
                ('events', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('failing', 'Failing')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
