# Generated by Django 6.0.6 on 2026-06-11 04:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medos', '0016_seed_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Hospital / organisation name', max_length=255)),
                ('slug', models.SlugField(help_text='Used in subdomain, e.g. citycare.medos.com', unique=True)),
                ('address', models.TextField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('logo_url', models.URLField(blank=True, default='')),
                ('registration_number', models.CharField(blank=True, default='', max_length=100)),
                ('plan', models.CharField(choices=[('basic', 'Basic'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='basic', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Deactivated = subscription expired / disabled')),
                ('subscription_expires_at', models.DateTimeField(blank=True, null=True)),
                ('license_key', models.CharField(blank=True, default='', max_length=200)),
                ('user_limit', models.IntegerField(default=0, help_text='Max allowed users (0 = unlimited)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'hospitals',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(help_text='Short code, e.g. CARD, ORTH', max_length=20),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='icuward',
            name='name',
            field=models.CharField(help_text='Ward name, e.g. Cardiac ICU', max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='masterdataentry',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='workflowdefinition',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='adminmodule',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_modules', to='medos.hospital'),
        ),
        migrations.AddField(
            model_name='aiinsight',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to='medos.hospital'),
        ),
        migrations.AddField(
            model_name='allergy',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='medos.hospital'),
        ),
        migrations.AddField(
            model_name='backuprecord',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backup_records', to='medos.hospital'),
        ),
        migrations.AddField(
            model_name='billingsettings',
            name='hospital',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_settings', to='medos.hospital'),
        ),
        migrations.AddField(
            model_name='careplan',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='care_plans', to='medos.hospital'),
        ),
        migrations.AddField(
            model_name='clinicalnote',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinical_notes', to='medos.hospital'),
        ),
        migrations.AddField(
            model_name='datapolicysettings',
            name='hospital',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_policy_settings', to='medos.hospital'),
        ),
        migrations.AddField(
            model_name='department',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='medos.hospital'),
        ),
        migrations.AddField(
            model_name='deviceintegration',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_integrations', to='medos.hospital'),
        ),
        migrations.AddField(
            model_name='encounter',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='medos.hospital'),
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to='medos.hospital'),
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='hospital',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='medos.hospital'),
        ),
        migrations.AddField(
            model_name='hospitaluserprofile',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_profiles', to='medos.hospital'),
        ),
        migrations.AddField(
            model_name='icubed',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='icu_beds', to='medos.hospital'),
        ),
        migrations.AddField(
            model_name='icuward',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='icu_wards', to='medos.hospital'),
        ),
        migrations.AddField(
            model_name='imagingresult',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imaging_results', to='medos.hospital'),
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurance_claims', to='medos.hospital'),
        ),
        migrations.AddField(
            model_name='integrationsetting',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integration_settings', to='medos.hospital'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='medos.hospital'),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_line_items', to='medos.hospital'),
        ),
        migrations.AddField(
            model_name='labalert',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_alerts', to='medos.hospital'),
        ),
        migrations.AddField(
            model_name='labdocument',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_documents', to='medos.hospital'),
        ),
        migrations.AddField(
            model_name='labinventory',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_inventory', to='medos.hospital'),
        ),
        migrations.AddField(
            model_name='laboratorysettings',
            name='hospital',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laboratory_settings', to='medos.hospital'),
        ),
        migrations.AddField(
            model_name='laborder',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to='medos.hospital'),
        ),
        migrations.AddField(
            model_name='labparameterresult',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_parameter_results', to='medos.hospital'),
        ),
        migrations.AddField(
            model_name='labresult',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to='medos.hospital'),
        ),
        migrations.AddField(
            model_name='licenseinfo',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='license_infos', to='medos.hospital'),
        ),
        migrations.AddField(
            model_name='localizationsettings',
            name='hospital',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='localization_settings', to='medos.hospital'),
        ),
        migrations.AddField(
            model_name='masterdataentry',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='master_data_entries', to='medos.hospital'),
        ),
        migrations.AddField(
            model_name='medicalalert',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_alerts', to='medos.hospital'),
        ),
        migrations.AddField(
            model_name='medication',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='medos.hospital'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='hospital',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to='medos.hospital'),
        ),
        migrations.AddField(
            model_name='patient',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='medos.hospital'),
        ),
        migrations.AddField(
            model_name='patientdocument',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_documents', to='medos.hospital'),
        ),
        migrations.AddField(
            model_name='patientinsurance',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_insurances', to='medos.hospital'),
        ),
        migrations.AddField(
            model_name='payment',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='medos.hospital'),
        ),
        migrations.AddField(
            model_name='pharmacysettings',
            name='hospital',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_settings', to='medos.hospital'),
        ),
        migrations.AddField(
            model_name='qcentry',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_qc_entries', to='medos.hospital'),
        ),
        migrations.AddField(
            model_name='reconciliationlog',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_logs', to='medos.hospital'),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refund_requests', to='medos.hospital'),
        ),
        migrations.AddField(
            model_name='saveddashboardview',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_dashboard_views', to='medos.hospital'),
        ),
        migrations.AddField(
            model_name='scheduledreport',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_reports', to='medos.hospital'),
        ),
        migrations.AddField(
            model_name='securitypolicy',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='security_policies', to='medos.hospital'),
        ),
        migrations.AddField(
            model_name='storagemetrics',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storage_metrics', to='medos.hospital'),
        ),
        migrations.AddField(
            model_name='syncentry',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sync_entries', to='medos.hospital'),
        ),
        migrations.AddField(
            model_name='systemactivitylog',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='medos.hospital'),
        ),
        migrations.AddField(
            model_name='systemalert',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='system_alerts', to='medos.hospital'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='system_settings', to='medos.hospital'),
        ),
        migrations.AddField(
            model_name='teleconsultsession',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teleconsult_sessions', to='medos.hospital'),
        ),
        migrations.AddField(
            model_name='teleicusession',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teleicu_sessions', to='medos.hospital'),
        ),
        migrations.AddField(
            model_name='teleicusettings',
            name='hospital',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teleicu_settings', to='medos.hospital'),
        ),
        migrations.AddField(
            model_name='template',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='medos.hospital'),
        ),
        migrations.AddField(
            model_name='testpanel',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_panels', to='medos.hospital'),
        ),
        migrations.AddField(
            model_name='testparameter',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_parameters', to='medos.hospital'),
        ),
        migrations.AddField(
            model_name='userloginactivity',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_activities', to='medos.hospital'),
        ),
        migrations.AddField(
            model_name='vitals',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vitals_set', to='medos.hospital'),
        ),
        migrations.AddField(
            model_name='webhook',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='medos.hospital'),
        ),
        migrations.AddField(
            model_name='workflowdefinition',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_definitions', to='medos.hospital'),
        ),
        migrations.AlterUniqueTogether(
            name='masterdataentry',
            unique_together={('hospital', 'category', 'key')},
        ),
        migrations.AlterUniqueTogether(
            name='workflowdefinition',
            unique_together={('hospital', 'module', 'name')},
        ),
    ]
