# Generated by Django 6.0.6 on 2026-06-11 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medos', '0017_hospital_alter_department_code_alter_department_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='medos.hospital'),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('name', 'hospital')},
        ),
    ]
