# Generated by Django 6.0.6 on 2026-06-11 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medos', '0018_role_hospital_alter_role_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitaluserprofile',
            name='must_change_password',
            field=models.BooleanField(default=True, help_text='User must reset password on next login'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
