# Generated by Django 6.0.6 on 2026-06-11 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medos', '0019_hospitaluserprofile_must_change_password_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospital',
            options={'managed': True, 'ordering': ['name'], 'verbose_name_plural': 'hospitals'},
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='medos.hospital'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_orders', to='medos.hospital'),
        ),
        migrations.AddIndex(
            model_name='diagnosis',
            index=models.Index(fields=['hospital'], name='medos_diagn_hospita_d41827_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceorder',
            index=models.Index(fields=['hospital'], name='medos_servi_hospita_afcb11_idx'),
        ),
    ]
