# Generated by Django 6.0.6 on 2026-06-12 00:50

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medos', '0021_appointments_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('generic_name', models.CharField(blank=True, default='', max_length=200)),
                ('brand_names', models.CharField(blank=True, default='', help_text='Comma-separated', max_length=500)),
                ('category', models.CharField(choices=[('ANALGESIC', 'Analgesic'), ('ANTIBIOTIC', 'Antibiotic'), ('ANTIVIRAL', 'Antiviral'), ('CARDIOVASCULAR', 'Cardiovascular'), ('CNS', 'Central Nervous System'), ('DIABETIC', 'Diabetic'), ('GASTROINTESTINAL', 'Gastrointestinal'), ('RESPIRATORY', 'Respiratory'), ('VITAMIN', 'Vitamin & Supplement'), ('VACCINE', 'Vaccine'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('dosage_form', models.CharField(blank=True, default='', help_text='e.g. Tablet, Capsule, Syrup, Injection', max_length=50)),
                ('strength', models.CharField(blank=True, default='', help_text='e.g. 500mg, 10mg/5ml', max_length=100)),
                ('is_controlled', models.BooleanField(default=False, help_text='Controlled / scheduled substance')),
                ('requires_prescription', models.BooleanField(default=True)),
                ('known_interactions', models.TextField(blank=True, default='', help_text='Comma-separated drug names this interacts with')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drugs', to='medos.hospital')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('hospital', 'name', 'strength')},
            },
        ),
        migrations.CreateModel(
            name='DrugInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(blank=True, default='', max_length=100)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit', models.CharField(default='units', help_text='Tablets, ml, vials, etc.', max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('reorder_level', models.DecimalField(decimal_places=2, default=10, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='medos.drug')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drug_inventory', to='medos.hospital')),
            ],
            options={
                'verbose_name_plural': 'drug inventories',
            },
        ),
        migrations.CreateModel(
            name='Dispensation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('drug_name', models.CharField(max_length=200)),
                ('dosage', models.CharField(blank=True, default='', max_length=100)),
                ('quantity_dispensed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(default='units', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DISPENSED', 'Dispensed'), ('PARTIAL', 'Partially Dispensed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('dispensed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dispensed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensations_made', to=settings.AUTH_USER_MODEL)),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispensations', to='medos.encounter')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispensations', to='medos.hospital')),
                ('medication', models.ForeignKey(blank=True, help_text='Link to the prescribed medication (optional for ad-hoc)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispensations', to='medos.medication')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispensations', to='medos.patient')),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensations', to='medos.druginventory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='druginventory',
            index=models.Index(fields=['hospital', 'drug'], name='medos_drugi_hospita_d1165b_idx'),
        ),
        migrations.AddIndex(
            model_name='druginventory',
            index=models.Index(fields=['expiry_date'], name='medos_drugi_expiry__0589db_idx'),
        ),
    ]
