# Generated by Django 6.0.6 on 2026-06-12 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medos', '0022_pharmacy_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('OPD', 'OPD Consultation'), ('PHARMACY', 'Pharmacy'), ('LAB', 'Lab Test'), ('IPD', 'Inpatient'), ('WALKIN', 'Walk-in Service'), ('TELEICU', 'TeleICU')], max_length=20),
        ),
        migrations.AlterField(
            model_name='medication',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='medos.encounter'),
        ),
    ]
