# Generated by Django 6.0.6 on 2026-06-12 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medos', '0023_alter_invoice_invoice_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, help_text='How many units / tablets / ml to dispense', max_digits=10),
        ),
        migrations.AddField(
            model_name='medication',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price per unit from DrugInventory', max_digits=10),
        ),
    ]
