# Generated by Django 6.0.6 on 2026-06-12 13:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medos', '0024_medication_quantity_medication_unit_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='cancellation_reason',
            field=models.TextField(blank=True, default='', help_text='Reason if this specific medication is cancelled'),
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft — only visible to the ordering doctor'), ('ORDERED', 'Ordered — visible to pharmacy/lab'), ('IN_PROGRESS', 'In Progress — pharmacy/lab has started'), ('DISPENSED', 'Dispensed — all items fulfilled'), ('CANCELLED', 'Cancelled — entire prescription voided'), ('AMENDED', 'Amended — superseded by a newer version')], default='DRAFT', max_length=20)),
                ('version', models.PositiveIntegerField(default=1, help_text='Auto-increments per encounter on each amendment')),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('cancellation_reason', models.TextField(blank=True, default='', help_text='Required when status is CANCELLED or AMENDED')),
                ('pharmacy_notes', models.TextField(blank=True, default='', help_text='Optional note from pharmacist')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='medos.encounter')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='medos.hospital')),
                ('ordered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions_ordered', to=settings.AUTH_USER_MODEL)),
                ('superseded_by', models.ForeignKey(blank=True, help_text='Newer version that replaces this one (null if latest)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='medos.prescription')),
            ],
            options={
                'ordering': ['-ordered_at'],
            },
        ),
        migrations.AddField(
            model_name='laborder',
            name='prescription',
            field=models.ForeignKey(blank=True, help_text='The prescription this lab order belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_orders', to='medos.prescription'),
        ),
        migrations.AddField(
            model_name='medication',
            name='prescription',
            field=models.ForeignKey(blank=True, help_text='The prescription this medication belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medications', to='medos.prescription'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['encounter', '-version'], name='medos_presc_encount_c20b64_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['status', 'hospital'], name='medos_presc_status_c9d9c1_idx'),
        ),
    ]
