# Generated by Django 6.0.6 on 2026-06-13 06:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medos', '0025_medication_cancellation_reason_prescription_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. General Ward 3A', max_length=100)),
                ('ward_type', models.CharField(choices=[('general', 'General'), ('surgical', 'Surgical'), ('maternity', 'Maternity'), ('paediatric', 'Paediatric'), ('orthopaedic', 'Orthopaedic'), ('private', 'Private'), ('semi_private', 'Semi-Private'), ('icu', 'ICU')], default='general', max_length=20)),
                ('bed_charge_per_day', models.DecimalField(decimal_places=2, default=Decimal('2000.00'), help_text='Daily bed charge in INR', max_digits=10)),
                ('floor', models.CharField(blank=True, default='', help_text='Floor / wing / building', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='medos.hospital')),
            ],
            options={
                'db_table': 'medos_ward',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bed_number', models.CharField(help_text='e.g. 3A-01', max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved'), ('maintenance', 'Maintenance')], default='available', max_length=20)),
                ('notes', models.CharField(blank=True, default='', help_text='Optional notes (e.g. needs repair, reserved for VIP)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_encounter', models.OneToOneField(blank=True, help_text='The currently admitted patient encounter', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bed', to='medos.encounter')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='medos.hospital')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='medos.ward')),
            ],
            options={
                'db_table': 'medos_bed',
                'ordering': ['ward__name', 'bed_number'],
            },
        ),
        migrations.CreateModel(
            name='BillingAccrual',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accrual_type', models.CharField(choices=[('bed_charge', 'Bed Charge'), ('nursing_charge', 'Nursing Charge'), ('miscellaneous', 'Miscellaneous')], default='bed_charge', max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('date', models.DateField(help_text='The date this charge applies to')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_invoiced', models.BooleanField(default=False, help_text='Has this been included in an invoice yet?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_accruals', to='medos.encounter')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_accruals', to='medos.hospital')),
            ],
            options={
                'db_table': 'medos_billingaccrual',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['encounter', 'is_invoiced'], name='medos_billi_encount_f71bbf_idx'), models.Index(fields=['hospital', 'date'], name='medos_billi_hospita_78cdf9_idx')],
                'unique_together': {('encounter', 'accrual_type', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DailyRound',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('round_date', models.DateField(default=django.utils.timezone.localdate)),
                ('notes', models.TextField(blank=True, default='', help_text="Doctor's notes for this round")),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('finalised', 'Finalised')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conducted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_rounds', to=settings.AUTH_USER_MODEL)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_rounds', to='medos.encounter')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_rounds', to='medos.hospital')),
                ('prescription', models.OneToOneField(blank=True, help_text='The prescription submitted for this round', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_round', to='medos.prescription')),
            ],
            options={
                'db_table': 'medos_dailyround',
                'ordering': ['-round_date', '-created_at'],
                'indexes': [models.Index(fields=['encounter', '-round_date'], name='medos_daily_encount_93bf6f_idx'), models.Index(fields=['status'], name='medos_daily_status_f19a9b_idx')],
                'unique_together': {('encounter', 'round_date')},
            },
        ),
        migrations.CreateModel(
            name='MedicationAdministration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('administered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('dose_given', models.CharField(help_text='Actual dose given (e.g. 500mg, 1 tablet)', max_length=100)),
                ('route', models.CharField(blank=True, default='', help_text='Route administered (Oral, IV, IM, etc.)', max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('administered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_administrations', to=settings.AUTH_USER_MODEL)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_administrations', to='medos.encounter')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_administrations', to='medos.hospital')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrations', to='medos.medication')),
            ],
            options={
                'db_table': 'medos_medicationadministration',
                'ordering': ['-administered_at'],
                'indexes': [models.Index(fields=['encounter', '-administered_at'], name='medos_medic_encount_392aaf_idx'), models.Index(fields=['medication'], name='medos_medic_medicat_b709c2_idx')],
            },
        ),
        migrations.CreateModel(
            name='NursingNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nursing_notes', to='medos.encounter')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nursing_notes', to='medos.hospital')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nursing_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'medos_nursingnote',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['encounter', '-created_at'], name='medos_nursi_encount_d43eaf_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='ward',
            index=models.Index(fields=['hospital', 'is_active'], name='medos_ward_hospita_a958f6_idx'),
        ),
        migrations.AddIndex(
            model_name='ward',
            index=models.Index(fields=['ward_type'], name='medos_ward_ward_ty_4a7df2_idx'),
        ),
        migrations.AddIndex(
            model_name='bed',
            index=models.Index(fields=['ward', 'status'], name='medos_bed_ward_id_6e80c0_idx'),
        ),
        migrations.AddIndex(
            model_name='bed',
            index=models.Index(fields=['hospital', 'status'], name='medos_bed_hospita_01d9f0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bed',
            unique_together={('ward', 'bed_number')},
        ),
    ]
