# Generated by Django 6.0.6 on 2026-06-13 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medos', '0026_ward_bed_billingaccrual_dailyround_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='department_ref',
            field=models.ForeignKey(blank=True, help_text='Reference to the Department model for data integrity', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encounters', to='medos.department'),
        ),
    ]
