"""
Seed Indian-generic drug-drug interactions.

Indian doctors prescribe by generic/salt names (e.g., Metformin,
Amlodipine, Telmisartan). This command populates ~200 clinically
relevant DDIs using Indian generic naming conventions.

Sources:
  - DDInter (extrapolated for Indian generics)
  - OpenFDA Adverse Event Reporting
  - DrugBank (open access)
"""
from django.core.management.base import BaseCommand
from medos.models import DrugInteraction

INTERACTIONS = [
    # ═══════════════════════════════════════════
    # CARDIOVASCULAR interactions
    # ═══════════════════════════════════════════
    # Amlodipine + Beta-blockers → additive BP reduction, bradycardia risk
    {"drug_a": "Amlodipine", "drug_b": "Atenolol", "severity": "moderate",
     "description": "Additive hypotensive effect. Risk of bradycardia and dizziness.",
     "mechanism": "Synergistic AV node suppression and vasodilation.",
     "recommendation": "Monitor BP and HR. Consider dose reduction if symptoms develop.",
     "source": "DDInter"},
    {"drug_a": "Amlodipine", "drug_b": "Metoprolol", "severity": "moderate",
     "description": "Additive hypotensive effect. Risk of bradycardia.",
     "mechanism": "Synergistic AV node suppression and vasodilation.",
     "recommendation": "Monitor BP and HR. Consider dose reduction if symptoms develop.",
     "source": "DDInter"},
    # Telmisartan + Ramipril → double RAAS blockade
    {"drug_a": "Telmisartan", "drug_b": "Ramipril", "severity": "major",
     "description": "Dual RAAS blockade increases risk of hypotension, hyperkalemia, and renal impairment.",
     "mechanism": "Additive ACE inhibition and AT1 receptor blockade.",
     "recommendation": "Avoid combination. Use single RAAS agent. Monitor K+ and creatinine if unavoidable.",
     "source": "OpenFDA"},
    {"drug_a": "Losartan", "drug_b": "Ramipril", "severity": "major",
     "description": "Dual RAAS blockade increases risk of hypotension, hyperkalemia, and renal impairment.",
     "mechanism": "Additive ACE inhibition and AT1 receptor blockade.",
     "recommendation": "Avoid combination. Use single RAAS agent. Monitor K+ and creatinine if unavoidable.",
     "source": "OpenFDA"},
    {"drug_a": "Telmisartan", "drug_b": "Enalapril", "severity": "major",
     "description": "Dual RAAS blockade — increased risk of hypotension and hyperkalemia.",
     "mechanism": "Additive ACE inhibition and AT1 receptor blockade.",
     "recommendation": "Avoid. Use single RAAS agent. Monitor K+ if unavoidable.",
     "source": "DDInter"},
    {"drug_a": "Losartan", "drug_b": "Enalapril", "severity": "major",
     "description": "Dual RAAS blockade — increased risk of hypotension and hyperkalemia.",
     "mechanism": "Additive ACE inhibition and AT1 receptor blockade.",
     "recommendation": "Avoid combination. Monitor renal function and K+.",
     "source": "DDInter"},
    # Spironolactone + RAAS blockers → hyperkalemia
    {"drug_a": "Spironolactone", "drug_b": "Ramipril", "severity": "major",
     "description": "Combined K+-sparing diuretic + ACE inhibitor increases hyperkalemia risk.",
     "mechanism": "Aldosterone antagonism plus ACE inhibition reduces K+ excretion.",
     "recommendation": "Monitor K+ closely. Limit dietary K+ intake. Consider reducing spironolactone dose.",
     "source": "DrugBank"},
    {"drug_a": "Spironolactone", "drug_b": "Telmisartan", "severity": "major",
     "description": "ARB + K+-sparing diuretic increases hyperkalemia risk.",
     "mechanism": "Aldosterone antagonism plus AT1 blockade reduces K+ excretion.",
     "recommendation": "Monitor K+ regularly. Avoid if baseline K+ >5.0.",
     "source": "DrugBank"},
    {"drug_a": "Spironolactone", "drug_b": "Losartan", "severity": "major",
     "description": "ARB + K+-sparing diuretic increases hyperkalemia risk.",
     "mechanism": "Aldosterone antagonism plus AT1 blockade reduces K+ excretion.",
     "recommendation": "Monitor K+ regularly. Avoid if baseline K+ >5.0.",
     "source": "DDInter"},
    # Digoxin + Diuretics → toxicity
    {"drug_a": "Digoxin", "drug_b": "Furosemide", "severity": "major",
     "description": "Loop diuretic-induced hypokalemia increases digoxin toxicity risk (arrhythmias, nausea).",
     "mechanism": "Furosemide depletes K+ and Mg++, reducing digoxin therapeutic window.",
     "recommendation": "Monitor K+ and Mg++. Maintain K+ >4.0. Consider K+ supplementation.",
     "source": "DDInter"},
    {"drug_a": "Digoxin", "drug_b": "Hydrochlorothiazide", "severity": "major",
     "description": "Thiazide-induced hypokalemia increases digoxin toxicity risk.",
     "mechanism": "HCTZ depletes K+, potentiating digoxin arrhythmogenicity.",
     "recommendation": "Monitor K+. Maintain K+ >4.0. Consider K+ supplementation.",
     "source": "DrugBank"},
    {"drug_a": "Digoxin", "drug_b": "Amiodarone", "severity": "major",
     "description": "Amiodarone increases digoxin levels by 70-100%. Risk of bradycardia and toxicity.",
     "mechanism": "Amiodarone reduces renal digoxin clearance and displaces tissue binding.",
     "recommendation": "Reduce digoxin dose by 50% on starting amiodarone. Monitor levels and ECG.",
     "source": "DDInter"},
    # Clopidogrel + PPIs
    {"drug_a": "Clopidogrel", "drug_b": "Omeprazole", "severity": "moderate",
     "description": "Omeprazole reduces clopidogrel activation via CYP2C19, potentially reducing antiplatelet effect.",
     "mechanism": "CYP2C19 inhibition by omeprazole reduces conversion to active metabolite.",
     "recommendation": "Use pantoprazole or rabeprazole instead (less CYP2C19 interaction).",
     "source": "DDInter"},
    {"drug_a": "Clopidogrel", "drug_b": "Pantoprazole", "severity": "minor",
     "description": "Minimal interaction. Pantoprazole has weaker CYP2C19 inhibition.",
     "mechanism": "Pantoprazole undergoes non-enzymatic metabolism, minimal CYP interaction.",
     "recommendation": "Safe for concurrent use. No dose adjustment needed.",
     "source": "DrugBank"},
    # Statin + Fibrate
    {"drug_a": "Atorvastatin", "drug_b": "Fenofibrate", "severity": "moderate",
     "description": "Increased risk of myopathy and rhabdomyolysis with statin-fibrate combination.",
     "mechanism": "Additive HMG-CoA reductase inhibition and PPAR-alpha activation.",
     "recommendation": "Monitor CK levels. Advise patient to report muscle pain. Avoid in renal impairment.",
     "source": "DDInter"},
    {"drug_a": "Rosuvastatin", "drug_b": "Fenofibrate", "severity": "moderate",
     "description": "Increased risk of myopathy with statin-fibrate combination.",
     "mechanism": "Additive effect on skeletal muscle.",
     "recommendation": "Monitor CK. Use lowest effective statin dose. Avoid in renal impairment.",
     "source": "OpenFDA"},
    # Aspirin + NSAIDs
    {"drug_a": "Aspirin", "drug_b": "Ibuprofen", "severity": "moderate",
     "description": "Ibuprofen may reduce aspirin's antiplatelet effect and increase GI bleeding risk.",
     "mechanism": "Competitive inhibition of COX-1 acetylation; additive GI mucosal damage.",
     "recommendation": "Take ibuprofen at least 30 min after aspirin. Consider gastroprotection.",
     "source": "DDInter"},
    {"drug_a": "Aspirin", "drug_b": "Diclofenac", "severity": "moderate",
     "description": "Increased GI bleeding risk with NSAID + aspirin combination.",
     "mechanism": "Additive COX-1 inhibition leading to gastric mucosal damage.",
     "recommendation": "Add PPI for gastroprotection. Use lowest NSAID dose, shortest duration.",
     "source": "DrugBank"},
    {"drug_a": "Aspirin", "drug_b": "Aceclofenac", "severity": "moderate",
     "description": "Increased GI bleeding risk. Additive COX-1 inhibition.",
     "mechanism": "Additive COX-1 inhibition leading to gastric mucosal injury.",
     "recommendation": "Consider gastroprotection with PPI. Monitor for GI symptoms.",
     "source": "DDInter"},
    # Warfarin/Acenocoumarol interactions
    {"drug_a": "Acenocoumarol", "drug_b": "Aspirin", "severity": "major",
     "description": "Significantly increased bleeding risk. Avoid combination if possible.",
     "mechanism": "Additive anticoagulant and antiplatelet effects.",
     "recommendation": "Avoid. If unavoidable, monitor INR closely. Use lowest effective doses.",
     "source": "DDInter"},
    {"drug_a": "Acenocoumarol", "drug_b": "Metronidazole", "severity": "major",
     "description": "Metronidazole potentiates anticoagulant effect — INR may double.",
     "mechanism": "Metronidazole inhibits hepatic metabolism of oral anticoagulants.",
     "recommendation": "Monitor INR every 2-3 days during and for 1 week after metronidazole course.",
     "source": "DrugBank"},
    {"drug_a": "Acenocoumarol", "drug_b": "Ciprofloxacin", "severity": "major",
     "description": "Fluoroquinolones potentiate anticoagulant effect. Increased INR.",
     "mechanism": "Ciprofloxacin inhibits CYP1A2, reducing anticoagulant metabolism.",
     "recommendation": "Monitor INR closely (every 2-3 days). Adjust dose as needed.",
     "source": "DDInter"},
    {"drug_a": "Acenocoumarol", "drug_b": "Rifampicin", "severity": "major",
     "description": "Rifampicin dramatically reduces anticoagulant effect via enzyme induction.",
     "mechanism": "Rifampicin induces CYP2C9, increasing anticoagulant metabolism.",
     "recommendation": "Monitor INR frequently. May need 2-3x dose increase. Warn patient.",
     "source": "DrugBank"},
    {"drug_a": "Acenocoumarol", "drug_b": "Phenylbutazone", "severity": "contraindicated",
     "description": "Contraindicated. Phenylbutazone potentiates anticoagulant effect with severe bleeding risk.",
     "mechanism": "CYP inhibition. Displaces protein binding.",
     "recommendation": "DO NOT USE together. Choose alternative NSAID.",
     "source": "DDInter"},

    # ═══════════════════════════════════════════
    # DIABETES / OAD interactions
    # ═══════════════════════════════════════════
    # Metformin + other OADs → hypoglycemia
    {"drug_a": "Metformin", "drug_b": "Glimepiride", "severity": "moderate",
     "description": "Additive hypoglycemic effect. Monitor blood glucose closely.",
     "mechanism": "Combined biguanide + sulfonylurea increases insulin secretion and sensitivity.",
     "recommendation": "Monitor fasting and post-prandial glucose. Educate patient on hypoglycemia symptoms.",
     "source": "DDInter"},
    {"drug_a": "Metformin", "drug_b": "Glipizide", "severity": "moderate",
     "description": "Additive hypoglycemic effect. Increased risk of hypoglycemia.",
     "mechanism": "Combined biguanide + sulfonylurea action.",
     "recommendation": "Glucose monitoring. Adjust sulfonylurea dose if needed.",
     "source": "DrugBank"},
    {"drug_a": "Metformin", "drug_b": "Insulin Glargine", "severity": "moderate",
     "description": "Additive glucose-lowering effect. Adjust insulin dose to avoid hypoglycemia.",
     "mechanism": "Combined insulin sensitizer plus exogenous insulin.",
     "recommendation": "Monitor glucose. Start insulin at low dose and titrate.",
     "source": "DDInter"},
    {"drug_a": "Metformin", "drug_b": "Pioglitazone", "severity": "minor",
     "description": "Additive glucose lowering. Usually a well-tolerated combination.",
     "mechanism": "Dual insulin sensitizer effect (AMPK + PPAR-γ).",
     "recommendation": "Monitor HbA1c. Watch for fluid retention with pioglitazone.",
     "source": "DrugBank"},
    # Glimepiride + other drugs → hypoglycemia
    {"drug_a": "Glimepiride", "drug_b": "Propranolol", "severity": "moderate",
     "description": "Beta-blockers mask hypoglycemia symptoms (tachycardia, palpitations). Increased hypoglycemia risk.",
     "mechanism": "Beta-blockade blunts adrenergic response to hypoglycemia.",
     "recommendation": "Warn patient about masked hypoglycemia. Monitor glucose more frequently.",
     "source": "DDInter"},
    {"drug_a": "Glimepiride", "drug_b": "Fluconazole", "severity": "major",
     "description": "Fluconazole increases glimepiride levels — severe hypoglycemia risk.",
     "mechanism": "Fluconazole inhibits CYP2C9 metabolism of glimepiride.",
     "recommendation": "Monitor glucose closely. Consider reducing glimepiride dose by 50%.",
     "source": "OpenFDA"},
    {"drug_a": "Glimepiride", "drug_b": "Clarithromycin", "severity": "moderate",
     "description": "Clarithromycin increases sulfonylurea levels — hypoglycemia risk.",
     "mechanism": "CYP3A4 inhibition reduces glimepiride metabolism.",
     "recommendation": "Monitor glucose. Consider temporary dose reduction.",
     "source": "DDInter"},
    # Dapagliflozin / Empagliflozin interactions
    {"drug_a": "Dapagliflozin", "drug_b": "Furosemide", "severity": "moderate",
     "description": "Additive volume depletion. Risk of hypotension and dehydration.",
     "mechanism": "Combined SGLT2 inhibition + loop diuretic enhances fluid loss.",
     "recommendation": "Monitor BP and renal function. Ensure adequate hydration.",
     "source": "DDInter"},
    {"drug_a": "Empagliflozin", "drug_b": "Furosemide", "severity": "moderate",
     "description": "Additive volume depletion risk. Combined diuretic effect.",
     "mechanism": "SGLT2 inhibition + loop diuretic — synergistic fluid loss.",
     "recommendation": "Monitor BP, electrolytes, and renal function.",
     "source": "DrugBank"},
    {"drug_a": "Dapagliflozin", "drug_b": "Insulin Glargine", "severity": "moderate",
     "description": "Additive glucose lowering. SGLT2 inhibitors reduce insulin dose requirement.",
     "mechanism": "SGLT2 inhibition reduces renal glucose reabsorption, independent of insulin.",
     "recommendation": "Reduce insulin dose by 10-20% when starting SGLT2 inhibitor. Monitor for DKA.",
     "source": "OpenFDA"},
    # Pioglitazone + Insulin
    {"drug_a": "Pioglitazone", "drug_b": "Insulin Glargine", "severity": "minor",
     "description": "Additive glucose lowering. Monitor for fluid retention.",
     "mechanism": "PPAR-γ agonist plus exogenous insulin.",
     "recommendation": "Monitor for edema and weight gain. Reduce insulin dose if needed.",
     "source": "DDInter"},
    # Acarbose + other OADs
    {"drug_a": "Acarbose", "drug_b": "Metformin", "severity": "minor",
     "description": "Additive glucose lowering. Well tolerated combination.",
     "mechanism": "Alpha-glucosidase inhibition + insulin sensitizer.",
     "recommendation": "Monitor post-prandial glucose. Treat hypoglycemia with glucose (not sucrose).",
     "source": "DrugBank"},

    # ═══════════════════════════════════════════
    # ANTI-INFECTIVE interactions
    # ═══════════════════════════════════════════
    # Rifampicin — major inducer
    {"drug_a": "Rifampicin", "drug_b": "Oral Contraceptives", "severity": "major",
     "description": "Rifampicin reduces contraceptive efficacy — risk of pregnancy.",
     "mechanism": "Strong CYP3A4 induction increases estrogen/progestin metabolism.",
     "recommendation": "Use alternative non-hormonal contraception during and for 4 weeks after rifampicin.",
     "source": "DDInter"},
    {"drug_a": "Rifampicin", "drug_b": "Metformin", "severity": "moderate",
     "description": "Rifampicin may reduce metformin efficacy.",
     "mechanism": "CYP induction and possible OATP inhibition affect metformin levels.",
     "recommendation": "Monitor blood glucose. Adjust metformin dose as needed.",
     "source": "OpenFDA"},
    {"drug_a": "Rifampicin", "drug_b": "Dapagliflozin", "severity": "moderate",
     "description": "Rifampicin may reduce dapagliflozin efficacy via UGT induction.",
     "mechanism": "UGT1A9 and UGT2B4 induction by rifampicin increases dapagliflozin metabolism.",
     "recommendation": "Monitor glucose. Consider dose adjustment.",
     "source": "DrugBank"},
    {"drug_a": "Isoniazid", "drug_b": "Rifampicin", "severity": "moderate",
     "description": "Combined hepatotoxicity risk. Rifampicin increases INH metabolite toxicity.",
     "mechanism": "Rifampicin induces hydrazine formation from INH, increasing liver injury risk.",
     "recommendation": "Monitor LFTs monthly. Warn patient about symptoms of hepatitis.",
     "source": "DDInter"},
    {"drug_a": "Isoniazid", "drug_b": "Carbamazepine", "severity": "major",
     "description": "INH increases carbamazepine levels — toxicity risk (ataxia, dizziness, sedation).",
     "mechanism": "INH inhibits CYP3A4, reducing carbamazepine metabolism.",
     "recommendation": "Monitor carbamazepine levels. Reduce dose by 20-30% if needed.",
     "source": "DrugBank"},
    {"drug_a": "Isoniazid", "drug_b": "Phenytoin", "severity": "major",
     "description": "INH increases phenytoin levels — toxicity risk.",
     "mechanism": "INH inhibits CYP2C9/2C19, reducing phenytoin metabolism.",
     "recommendation": "Monitor phenytoin levels. Reduce phenytoin dose by 30%.",
     "source": "DDInter"},
    # Metronidazole
    {"drug_a": "Metronidazole", "drug_b": "Alcohol", "severity": "major",
     "description": "Disulfiram-like reaction: severe nausea, vomiting, flushing, headache.",
     "mechanism": "Metronidazole inhibits aldehyde dehydrogenase, causing acetaldehyde accumulation.",
     "recommendation": "Advise complete avoidance of alcohol during treatment and for 48h after last dose.",
     "source": "DrugBank"},
    # Fluoroquinolones
    {"drug_a": "Levofloxacin", "drug_b": "NSAIDs", "severity": "moderate",
     "description": "Increased CNS stimulation risk (seizures, dizziness). Avoid in epilepsy.",
     "mechanism": "GABA-A receptor antagonism is potentiated by NSAIDs.",
     "recommendation": "Avoid combination in patients with seizure history. Use caution.",
     "source": "DDInter"},
    {"drug_a": "Ciprofloxacin", "drug_b": "Theophylline", "severity": "major",
     "description": "Ciprofloxacin increases theophylline levels — toxicity risk (seizures, arrhythmias).",
     "mechanism": "Ciprofloxacin inhibits CYP1A2, reducing theophylline clearance by 30-50%.",
     "recommendation": "Reduce theophylline dose by 50%. Monitor theophylline levels.",
     "source": "DDInter"},
    {"drug_a": "Levofloxacin", "drug_b": "Theophylline", "severity": "moderate",
     "description": "Levofloxacin may increase theophylline levels. Less interaction than ciprofloxacin.",
     "mechanism": "Weak CYP1A2 inhibition.",
     "recommendation": "Monitor theophylline levels. Dose adjustment may not be needed.",
     "source": "DrugBank"},
    # Macrolides
    {"drug_a": "Azithromycin", "drug_b": "Digoxin", "severity": "moderate",
     "description": "Azithromycin may increase digoxin levels via P-gp inhibition.",
     "mechanism": "P-glycoprotein inhibition in gut reduces digoxin efflux, increasing absorption.",
     "recommendation": "Monitor digoxin levels. Watch for signs of digoxin toxicity.",
     "source": "DDInter"},
    {"drug_a": "Azithromycin", "drug_b": "Atorvastatin", "severity": "moderate",
     "description": "Azithromycin may increase statin levels — myopathy risk.",
     "mechanism": "Macrolide inhibits CYP3A4 metabolism of statins.",
     "recommendation": "Monitor for muscle pain. Consider temporary statin dose reduction.",
     "source": "OpenFDA"},
    {"drug_a": "Clarithromycin", "drug_b": "Atorvastatin", "severity": "major",
     "description": "Clarithromycin significantly increases atorvastatin levels — rhabdomyolysis risk.",
     "mechanism": "Strong CYP3A4 inhibition by clarithromycin.",
     "recommendation": "Use azithromycin instead. If unavoidable, hold statin during clarithromycin course.",
     "source": "DDInter"},
    # Antifungals
    {"drug_a": "Fluconazole", "drug_b": "Atorvastatin", "severity": "moderate",
     "description": "Fluconazole increases statin levels — myopathy risk.",
     "mechanism": "CYP3A4 and CYP2C9 inhibition by fluconazole.",
     "recommendation": "Monitor for muscle pain. Consider reducing statin dose.",
     "source": "DrugBank"},
    {"drug_a": "Fluconazole", "drug_b": "Losartan", "severity": "moderate",
     "description": "Fluconazole reduces losartan active metabolite formation — reduced efficacy.",
     "mechanism": "CYP2C9 inhibition blocks conversion to active E-3174 metabolite.",
     "recommendation": "Monitor BP. Consider alternative ARB or increase losartan dose.",
     "source": "DDInter"},
    # Antimalarials
    {"drug_a": "Artesunate", "drug_b": "Mefloquine", "severity": "moderate",
     "description": "May reduce artesunate efficacy. Increased ECG monitoring recommended.",
     "mechanism": "Possible pharmacodynamic antagonism. QT prolongation additive.",
     "recommendation": "Monitor ECG. Use alternative partner drug if possible.",
     "source": "DDInter"},
    {"drug_a": "Artesunate", "drug_b": "Amiodarone", "severity": "major",
     "description": "Additive QT prolongation — risk of torsades de pointes.",
     "mechanism": "Both drugs prolong ventricular repolarization.",
     "recommendation": "Avoid combination. If unavoidable, monitor ECG and K+/Mg+.",
     "source": "OpenFDA"},
    # Anti-retrovirals (common in Indian ART)
    {"drug_a": "Tenofovir", "drug_b": "Acyclovir", "severity": "moderate",
     "description": "Additive nephrotoxicity. Both drugs are renally excreted.",
     "mechanism": "Competition for renal tubular secretion.",
     "recommendation": "Monitor renal function. Ensure adequate hydration.",
     "source": "DrugBank"},

    # ═══════════════════════════════════════════
    # NSAID / ANALGESIC interactions
    # ═══════════════════════════════════════════
    # Multiple NSAIDs
    {"drug_a": "Diclofenac", "drug_b": "Aspirin", "severity": "moderate",
     "description": "Increased GI bleeding risk. Additive COX inhibition.",
     "mechanism": "Additive COX-1 inhibition leads to gastric mucosal damage.",
     "recommendation": "Avoid combination. Add PPI if needed. Use single NSAID.",
     "source": "DDInter"},
    {"drug_a": "Diclofenac", "drug_b": "Ibuprofen", "severity": "moderate",
     "description": "No added benefit, increased GI and renal toxicity.",
     "mechanism": "Additive COX inhibition with no additional analgesia.",
     "recommendation": "Do NOT combine. Choose one NSAID at appropriate dose.",
     "source": "DrugBank"},
    {"drug_a": "Ibuprofen", "drug_b": "Paracetamol", "severity": "minor",
     "description": "Generally safe combination. Alternate for better pain control.",
     "mechanism": "Different analgesic mechanisms — COX inhibition + central COX-3.",
     "recommendation": "Commonly used combination in Indian practice. Safe at recommended doses.",
     "source": "DrugBank"},
    {"drug_a": "Diclofenac", "drug_b": "Paracetamol", "severity": "minor",
     "description": "Common combination in Indian practice. Generally safe short-term.",
     "mechanism": "Synergistic analgesia via COX and central pathways.",
     "recommendation": "Safe for short-term use. Avoid in active PUD.",
     "source": "DDInter"},
    # NSAIDs + Antihypertensives
    {"drug_a": "Diclofenac", "drug_b": "Ramipril", "severity": "moderate",
     "description": "NSAIDs reduce antihypertensive efficacy of ACE inhibitors. Risk of renal impairment.",
     "mechanism": "NSAIDs inhibit prostaglandin synthesis needed for ACE inhibitor action.",
     "recommendation": "Monitor BP and renal function. Consider alternative analgesia.",
     "source": "DDInter"},
    {"drug_a": "Ibuprofen", "drug_b": "Telmisartan", "severity": "moderate",
     "description": "NSAIDs reduce ARB antihypertensive effect. Risk of acute kidney injury.",
     "mechanism": "Prostaglandin inhibition reduces vasodilatory effect of ARBs.",
     "recommendation": "Monitor BP. Use lowest NSAID dose. Stay hydrated.",
     "source": "DrugBank"},
    {"drug_a": "Diclofenac", "drug_b": "Furosemide", "severity": "moderate",
     "description": "NSAIDs reduce diuretic efficacy and increase nephrotoxicity risk.",
     "mechanism": "COX inhibition reduces prostaglandin-mediated renal blood flow.",
     "recommendation": "Monitor renal function and urine output. Consider alternative analgesia.",
     "source": "DDInter"},
    # Tramadol + Serotonergic drugs
    {"drug_a": "Tramadol", "drug_b": "Amitriptyline", "severity": "major",
     "description": "Increased risk of serotonin syndrome and seizures. Both lower seizure threshold.",
     "mechanism": "Additive serotonergic effect. Both inhibit serotonin reuptake.",
     "recommendation": "Avoid combination. Use alternative analgesic if patient is on TCAs.",
     "source": "DDInter"},
    {"drug_a": "Tramadol", "drug_b": "Fluoxetine", "severity": "major",
     "description": "Serotonin syndrome risk: agitation, hyperthermia, clonus, hyperreflexia.",
     "mechanism": "Additive serotonin reuptake inhibition.",
     "recommendation": "Avoid. Use non-opioid analgesic. If unavoidable, start at lowest dose and monitor.",
     "source": "DDInter"},
    {"drug_a": "Tramadol", "drug_b": "Escitalopram", "severity": "major",
     "description": "Serotonin syndrome risk with SSRI + tramadol combination.",
     "mechanism": "Additive serotonin reuptake inhibition.",
     "recommendation": "Avoid combination. Choose alternative analgesic.",
     "source": "OpenFDA"},
    {"drug_a": "Tramadol", "drug_b": "Ondansetron", "severity": "moderate",
     "description": "Increased serotonin syndrome risk. Ondansetron is a 5-HT3 antagonist.",
     "mechanism": "Complex serotonergic interaction — ondansetron may reduce tramadol efficacy.",
     "recommendation": "Monitor for serotonin toxicity. Consider alternative antiemetic.",
     "source": "DDInter"},
    # Gabapentinoids
    {"drug_a": "Gabapentin", "drug_b": "Amitriptyline", "severity": "moderate",
     "description": "Additive sedation and dizziness. Common neuropathic pain combination.",
     "mechanism": "Synergistic CNS depression.",
     "recommendation": "Start at low doses. Warn about driving/machinery. Common but safe if titrated.",
     "source": "DrugBank"},
    {"drug_a": "Pregabalin", "drug_b": "Clonazepam", "severity": "moderate",
     "description": "Additive CNS depression — excessive sedation, reduced coordination.",
     "mechanism": "GABAergic potentiation plus calcium channel modulation.",
     "recommendation": "Reduce doses of both. Warn about driving and falls.",
     "source": "DDInter"},
    {"drug_a": "Gabapentin", "drug_b": "Codeine", "severity": "moderate",
     "description": "Additive respiratory depression and sedation risk.",
     "mechanism": "Synergistic CNS depression via GABA and opioid receptors.",
     "recommendation": "Monitor for excessive sedation. Reduce doses in elderly.",
     "source": "OpenFDA"},

    # ═══════════════════════════════════════════
    # GASTROINTESTINAL interactions
    # ═══════════════════════════════════════════
    # PPIs + Antiplatelets
    {"drug_a": "Omeprazole", "drug_b": "Clopidogrel", "severity": "moderate",
     "description": "Omeprazole reduces clopidogrel activation via CYP2C19 competition.",
     "mechanism": "CYP2C19 inhibition reduces active metabolite formation.",
     "recommendation": "Use pantoprazole or rabeprazole instead of omeprazole.",
     "source": "DDInter"},
    {"drug_a": "Pantoprazole", "drug_b": "Methotrexate", "severity": "moderate",
     "description": "PPIs may reduce methotrexate clearance — toxicity risk.",
     "mechanism": "Competitive inhibition of renal tubular secretion.",
     "recommendation": "Withhold PPI during high-dose methotrexate. Monitor levels.",
     "source": "DrugBank"},
    # Prokinetics
    {"drug_a": "Domperidone", "drug_b": "Amiodarone", "severity": "contraindicated",
     "description": "Contraindicated: additive QT prolongation, risk of torsades de pointes.",
     "mechanism": "Both drugs block hERG K+ channels, prolonging QT interval.",
     "recommendation": "DO NOT COMBINE. Use alternative antiemetic (ondansetron).",
     "source": "DDInter"},
    {"drug_a": "Domperidone", "drug_b": "Levofloxacin", "severity": "major",
     "description": "Additive QT prolongation. Risk of cardiac arrhythmias.",
     "mechanism": "Combined hERG channel blockade.",
     "recommendation": "Monitor ECG. Use alternative antiemetic or antibiotic if possible.",
     "source": "OpenFDA"},
    {"drug_a": "Domperidone", "drug_b": "Azithromycin", "severity": "moderate",
     "description": "Both drugs prolong QT interval. Moderate risk.",
     "mechanism": "hERG K+ channel blockade additive effect.",
     "recommendation": "Use in caution. Monitor ECG in elderly or those with cardiac disease.",
     "source": "DrugBank"},
    # Antacids + drugs
    {"drug_a": "Sucralfate", "drug_b": "Ciprofloxacin", "severity": "moderate",
     "description": "Sucralfate reduces fluoroquinolone absorption by >50%.",
     "mechanism": "Cationic binding — sucralfate contains aluminum ions that chelate quinolones.",
     "recommendation": "Space doses: ciprofloxacin 2h before or 6h after sucralfate.",
     "source": "DDInter"},
    {"drug_a": "Sucralfate", "drug_b": "Thyroxine", "severity": "major",
     "description": "Sucralfate reduces thyroxine absorption — may worsen hypothyroidism.",
     "mechanism": "Physical binding and reduced GI absorption.",
     "recommendation": "Space by at least 4 hours. Monitor TSH in 6-8 weeks.",
     "source": "DrugBank"},
    {"drug_a": "Antacids", "drug_b": "Ciprofloxacin", "severity": "moderate",
     "description": "Mg/Al-containing antacids reduce fluoroquinolone absorption by 50-90%.",
     "mechanism": "Cation chelation of quinolone ring.",
     "recommendation": "Take ciprofloxacin 2h before or 4h after antacid.",
     "source": "DDInter"},
    # Ondansetron
    {"drug_a": "Ondansetron", "drug_b": "Tramadol", "severity": "moderate",
     "description": "Ondansetron may reduce tramadol's analgesic efficacy. Serotonin syndrome risk.",
     "mechanism": "5-HT3 antagonism may block tramadol's serotonergic analgesia.",
     "recommendation": "Monitor pain control. Consider alternative antiemetic.",
     "source": "OpenFDA"},

    # ═══════════════════════════════════════════
    # RESPIRATORY interactions
    # ═══════════════════════════════════════════
    # Theophylline — narrow therapeutic index
    {"drug_a": "Theophylline", "drug_b": "Ciprofloxacin", "severity": "major",
     "description": "Ciprofloxacin increases theophylline levels by 30-50% — toxicity risk.",
     "mechanism": "CYP1A2 inhibition reduces theophylline clearance.",
     "recommendation": "Reduce theophylline dose by 50%. Monitor levels. Consider alternative antibiotic.",
     "source": "DDInter"},
    {"drug_a": "Deriphyllin", "drug_b": "Ciprofloxacin", "severity": "major",
     "description": "Ciprofloxacin increases deriphylline levels — toxicity risk.",
     "mechanism": "CYP1A2 inhibition.",
     "recommendation": "Reduce dose. Monitor for nausea, palpitations, seizures.",
     "source": "DDInter"},
    {"drug_a": "Theophylline", "drug_b": "Propranolol", "severity": "moderate",
     "description": "Beta-blockers reduce theophylline clearance and oppose bronchodilation.",
     "mechanism": "Pharmacodynamic antagonism on bronchial smooth muscle.",
     "recommendation": "Use cardioselective beta-blocker if needed. Monitor theophylline levels.",
     "source": "DrugBank"},
    # Montelukast
    {"drug_a": "Montelukast", "drug_b": "Aspirin", "severity": "minor",
     "description": "Aspirin may exacerbate asthma in sensitive patients. No direct interaction.",
     "mechanism": "Aspirin-sensitive asthma — leukotriene pathway.",
     "recommendation": "Warn about aspirin use in asthma. Montelukast may partially protect.",
     "source": "DrugBank"},

    # ═══════════════════════════════════════════
    # CNS / PSYCHIATRY interactions
    # ═══════════════════════════════════════════
    # SSRI + MAOI — classic
    {"drug_a": "Fluoxetine", "drug_b": "Linezolid", "severity": "contraindicated",
     "description": "Contraindicated: serotonin syndrome risk with MAO inhibitor activity.",
     "mechanism": "Linezolid has MAOI activity. Combined with SSRI causes serotonin excess.",
     "recommendation": "DO NOT COMBINE. Choose alternative antibiotic.",
     "source": "DDInter"},
    {"drug_a": "Escitalopram", "drug_b": "Linezolid", "severity": "contraindicated",
     "description": "Contraindicated: serotonin syndrome risk with MAO inhibitor activity.",
     "mechanism": "Linezolid MAOI + SSRI = serotonin excess.",
     "recommendation": "DO NOT COMBINE. Choose alternative antibiotic.",
     "source": "OpenFDA"},
    {"drug_a": "Sertraline", "drug_b": "Linezolid", "severity": "contraindicated",
     "description": "Contraindicated: serotonin syndrome risk.",
     "mechanism": "MAO inhibitor activity of linezolid plus SSRI.",
     "recommendation": "DO NOT COMBINE. Use alternative antibiotic.",
     "source": "DrugBank"},
    # SSRI + NSAIDs
    {"drug_a": "Escitalopram", "drug_b": "Diclofenac", "severity": "moderate",
     "description": "Increased bleeding risk. SSRIs impair platelet function; NSAIDs add GI bleeding.",
     "mechanism": "SSRI depletes platelet serotonin. NSAIDs inhibit COX-1.",
     "recommendation": "Add PPI for gastroprotection. Monitor for bruising/bleeding.",
     "source": "DDInter"},
    {"drug_a": "Fluoxetine", "drug_b": "Diclofenac", "severity": "moderate",
     "description": "Increased bleeding risk. SSRI + NSAID combination.",
     "mechanism": "Impaired platelet aggregation plus GI mucosal injury.",
     "recommendation": "Consider gastroprotection. Monitor for GI bleeding.",
     "source": "OpenFDA"},
    {"drug_a": "Sertraline", "drug_b": "Aspirin", "severity": "moderate",
     "description": "Increased bleeding risk. Additive effect on platelet function.",
     "mechanism": "SSRI depletes platelet serotonin + aspirin irreversibly inhibits COX-1.",
     "recommendation": "Consider PPI. Monitor for signs of bleeding.",
     "source": "DDInter"},
    # Antiepileptics
    {"drug_a": "Phenytoin", "drug_b": "Metronidazole", "severity": "major",
     "description": "Metronidazole increases phenytoin levels — toxicity risk.",
     "mechanism": "CYP2C9/2C19 inhibition by metronidazole.",
     "recommendation": "Monitor phenytoin levels. Reduce dose if needed.",
     "source": "DDInter"},
    {"drug_a": "Phenytoin", "drug_b": "Fluconazole", "severity": "major",
     "description": "Fluconazole significantly increases phenytoin levels — toxicity risk.",
     "mechanism": "CYP2C9 inhibition reduces phenytoin clearance.",
     "recommendation": "Monitor phenytoin levels. May need 30-50% dose reduction.",
     "source": "DrugBank"},
    {"drug_a": "Valproate", "drug_b": "Aspirin", "severity": "moderate",
     "description": "Aspirin displaces valproate from protein binding — increased free fraction, toxicity risk.",
     "mechanism": "Protein binding displacement and beta-oxidation inhibition.",
     "recommendation": "Monitor valproate levels. Watch for sedation, tremor, hepatotoxicity.",
     "source": "DDInter"},
    {"drug_a": "Valproate", "drug_b": "Clonazepam", "severity": "moderate",
     "description": "Additive CNS depression. Both potentiate GABA.",
     "mechanism": "Synergistic GABAergic effect.",
     "recommendation": "Monitor sedation. Use lowest effective doses.",
     "source": "DrugBank"},
    {"drug_a": "Carbamazepine", "drug_b": "Oral Contraceptives", "severity": "major",
     "description": "Carbamazepine reduces contraceptive efficacy via CYP3A4 induction.",
     "mechanism": "Strong CYP3A4 induction increases estrogen/progestin clearance.",
     "recommendation": "Use alternative contraception (higher-dose pill or non-hormonal).",
     "source": "DDInter"},
    {"drug_a": "Carbamazepine", "drug_b": "Atorvastatin", "severity": "moderate",
     "description": "Carbamazepine reduces statin levels — reduced efficacy.",
     "mechanism": "CYP3A4 induction increases statin metabolism.",
     "recommendation": "Monitor lipids. Consider increasing statin dose or using rosuvastatin.",
     "source": "OpenFDA"},
    # Antipsychotics
    {"drug_a": "Olanzapine", "drug_b": "Ciprofloxacin", "severity": "moderate",
     "description": "Ciprofloxacin increases olanzapine levels — sedation and metabolic effects.",
     "mechanism": "CYP1A2 inhibition reduces olanzapine clearance.",
     "recommendation": "Monitor for increased sedation. Consider reducing olanzapine dose.",
     "source": "DDInter"},
    {"drug_a": "Olanzapine", "drug_b": "Fluoxetine", "severity": "minor",
     "description": "Fluoxetine may increase olanzapine levels. Usually well tolerated.",
     "mechanism": "CYP2D6 and CYP1A2 interactions.",
     "recommendation": "Monitor weight and metabolic parameters. Common combination.",
     "source": "DrugBank"},

    # ═══════════════════════════════════════════
    # THYROID interactions
    # ═══════════════════════════════════════════
    {"drug_a": "Thyroxine", "drug_b": "Omeprazole", "severity": "moderate",
     "description": "PPIs reduce thyroxine absorption — may worsen hypothyroidism.",
     "mechanism": "Gastric pH elevation reduces thyroxine dissolution and absorption.",
     "recommendation": "Take thyroxine on empty stomach, 30 min before PPI. Monitor TSH.",
     "source": "DDInter"},
    {"drug_a": "Thyroxine", "drug_b": "Calcium Carbonate", "severity": "moderate",
     "description": "Calcium supplements reduce thyroxine absorption by 20-25%.",
     "mechanism": "Chelation of thyroxine molecules with calcium ions.",
     "recommendation": "Space by at least 4 hours. Common in postmenopausal women on both.",
     "source": "DrugBank"},
    {"drug_a": "Thyroxine", "drug_b": "Ferrous Sulfate", "severity": "moderate",
     "description": "Iron supplements reduce thyroxine absorption significantly.",
     "mechanism": "Physical binding between iron and thyroxine in GI tract.",
     "recommendation": "Space by at least 4 hours. Common in anemia + hypothyroidism patients.",
     "source": "DDInter"},
    {"drug_a": "Carbimazole", "drug_b": "Warfarin", "severity": "moderate",
     "description": "Antithyroid drugs reduce anticoagulant effect when hyperthyroid state corrects.",
     "mechanism": "Metabolic changes as thyroid normalizes affect clotting factor synthesis.",
     "recommendation": "Monitor INR frequently when starting carbimazole in warfarin patients.",
     "source": "OpenFDA"},
    {"drug_a": "Propylthiouracil", "drug_b": "Warfarin", "severity": "moderate",
     "description": "PTU potentiates warfarin effect — increased INR and bleeding risk.",
     "mechanism": "Reduced vitamin K-dependent clotting factor metabolism.",
     "recommendation": "Monitor INR. Reduce warfarin dose as thyroid function normalizes.",
     "source": "DDInter"},

    # ═══════════════════════════════════════════
    # HEMATOLOGY interactions
    # ═══════════════════════════════════════════
    {"drug_a": "Acenocoumarol", "drug_b": "Clopidogrel", "severity": "contraindicated",
     "description": "Contraindicated: triple therapy bleeding risk unless essential (e.g., recent stent).",
     "mechanism": "Dual anticoagulation + antiplatelet = multiplicative bleeding risk.",
     "recommendation": "Avoid unless indicated for mechanical valve + recent stent. Monitor INR closely.",
     "source": "DDInter"},
    {"drug_a": "Acenocoumarol", "drug_b": "Diclofenac", "severity": "major",
     "description": "NSAIDs with anticoagulant — significantly increased GI and systemic bleeding.",
     "mechanism": "COX-1 inhibition plus anticoagulation.",
     "recommendation": "Use paracetamol for analgesia. Add PPI if NSAID unavoidable.",
     "source": "DrugBank"},
    {"drug_a": "Acenocoumarol", "drug_b": "Amoxicillin", "severity": "moderate",
     "description": "Broad-spectrum antibiotics can potentiate anticoagulant effect.",
     "mechanism": "Gut flora reduction decreases vitamin K synthesis.",
     "recommendation": "Monitor INR during and 1-2 weeks after antibiotic course.",
     "source": "DDInter"},
    {"drug_a": "Enoxaparin", "drug_b": "Aspirin", "severity": "major",
     "description": "Increased bleeding risk with LMWH + antiplatelet combination.",
     "mechanism": "Additive anticoagulant and antiplatelet effects.",
     "recommendation": "Monitor for bleeding. Use lowest effective doses. Common in ACS protocols.",
     "source": "DDInter"},
    {"drug_a": "Tranexamic Acid", "drug_b": "Oral Contraceptives", "severity": "moderate",
     "description": "Increased thrombotic risk with tranexamic acid + estrogen combination.",
     "mechanism": "Additive prothrombotic effect.",
     "recommendation": "Avoid in women on OCPs. Use alternative haemostatic agent.",
     "source": "DrugBank"},
    {"drug_a": "Tranexamic Acid", "drug_b": "Enoxaparin", "severity": "moderate",
     "description": "Theoretical opposing effects. Tranexamic acid may reduce anticoagulant effect.",
     "mechanism": "Antifibrinolytic agent opposes LMWH's anticoagulant action.",
     "recommendation": "Use with caution. Monitor for thrombotic/thrombolytic balance.",
     "source": "DDInter"},

    # ═══════════════════════════════════════════
    # MISCELLANEOUS common Indian OTC interactions
    # ═══════════════════════════════════════════
    {"drug_a": "Cetirizine", "drug_b": "Alcohol", "severity": "minor",
     "description": "Additive sedation. Antihistamines potentiate alcohol effects.",
     "mechanism": "CNS depression additive effect.",
     "recommendation": "Avoid alcohol while taking antihistamines. Warn about driving.",
     "source": "DrugBank"},
    {"drug_a": "Levocetirizine", "drug_b": "Alcohol", "severity": "minor",
     "description": "Mild additive sedation. Less sedating than cetirizine.",
     "mechanism": "CNS depression additive effect.",
     "recommendation": "Advise caution with alcohol. Less sedating than first-gen antihistamines.",
     "source": "DrugBank"},
    {"drug_a": "Chlorpheniramine", "drug_b": "Amitriptyline", "severity": "moderate",
     "description": "Additive anticholinergic effects — dry mouth, constipation, urinary retention, confusion.",
     "mechanism": "Combined muscarinic receptor blockade.",
     "recommendation": "Avoid in elderly. Monitor for anticholinergic toxicity.",
     "source": "DDInter"},
    {"drug_a": "Dextromethorphan", "drug_b": "Fluoxetine", "severity": "moderate",
     "description": "Serotonin syndrome risk. Dextromethorphan has serotonergic activity.",
     "mechanism": "Additive serotonin reuptake inhibition.",
     "recommendation": "Monitor for serotonin syndrome. Use alternative antitussive.",
     "source": "OpenFDA"},
    {"drug_a": "Ambroxol", "drug_b": "Codeine", "severity": "minor",
     "description": "Cough suppression counteracts mucolytic expectorant effect minimally.",
     "mechanism": "Codeine suppresses cough reflex, reducing clearance of thinned secretions.",
     "recommendation": "Generally safe. Ensure adequate hydration.",
     "source": "DrugBank"},
    {"drug_a": "Potassium Supplements", "drug_b": "Spironolactone", "severity": "contraindicated",
     "description": "Life-threatening hyperkalemia risk with potassium supplementation + K-sparing diuretic.",
     "mechanism": "Combined K+ loading with reduced K+ excretion.",
     "recommendation": "DO NOT SUPPLEMENT K+ with K-sparing diuretics. Monitor K+ regularly.",
     "source": "DDInter"},
    {"drug_a": "Potassium Supplements", "drug_b": "Ramipril", "severity": "moderate",
     "description": "ACE inhibitors reduce K+ excretion — risk of hyperkalemia with supplements.",
     "mechanism": "ACE inhibition reduces aldosterone, decreasing K+ excretion.",
     "recommendation": "Avoid K+ supplements with ACE inhibitors unless deficiency confirmed.",
     "source": "DrugBank"},
    {"drug_a": "Folic Acid", "drug_b": "Methotrexate", "severity": "moderate",
     "description": "Folic acid supplementation may reduce methotrexate efficacy in RA.",
     "mechanism": "Dihydrofolate reductase inhibition bypassed by exogenous folate.",
     "recommendation": "Timing: give folic acid on days without methotrexate. Continue for side effect reduction.",
     "source": "DDInter"},
    {"drug_a": "Vitamin D", "drug_b": "Digoxin", "severity": "moderate",
     "description": "Vitamin D-induced hypercalcemia potentiates digoxin toxicity (arrhythmias, heart block).",
     "mechanism": "Hypercalcemia increases myocardial sensitivity to digoxin.",
     "recommendation": "Monitor serum calcium. Avoid high-dose vitamin D in patients on digoxin.",
     "source": "DrugBank"},
    {"drug_a": "Vitamin D", "drug_b": "Hydrochlorothiazide", "severity": "minor",
     "description": "Thiazide diuretics reduce urinary calcium excretion — mild hypercalcemia risk with high-dose vitamin D.",
     "mechanism": "HCTZ decreases Ca++ excretion, vitamin D increases absorption.",
     "recommendation": "Monitor serum calcium with high-dose vitamin D + thiazide.",
     "source": "DDInter"},
]

# COVID-19 / post-COVID interactions
INDIAN_COVID_INTERACTIONS = [
    {"drug_a": "Dexamethasone", "drug_b": "Aspirin", "severity": "moderate",
     "description": "Increased GI bleeding risk. Corticosteroid + NSAID combination.",
     "mechanism": "Corticosteroids impair mucosal defense; aspirin adds COX inhibition.",
     "recommendation": "Add PPI. Use lowest steroid dose and shortest duration.",
     "source": "OpenFDA"},
    {"drug_a": "Dexamethasone", "drug_b": "Insulin Glargine", "severity": "moderate",
     "description": "Steroids cause hyperglycemia — significantly increased insulin requirement.",
     "mechanism": "Corticosteroid-induced insulin resistance.",
     "recommendation": "Monitor blood glucose 4-6 hourly. Titrate insulin aggressively.",
     "source": "DDInter"},
    {"drug_a": "Dexamethasone", "drug_b": "Glimepiride", "severity": "moderate",
     "description": "Steroid-induced hyperglycemia may require increased OAD dose.",
     "mechanism": "Corticosteroid-induced insulin resistance.",
     "recommendation": "Monitor glucose. May need temporary insulin.",
     "source": "DrugBank"},
    {"drug_a": "Enoxaparin", "drug_b": "Clopidogrel", "severity": "major",
     "description": "Increased bleeding risk. Common in COVID-19 thromboprophylaxis.",
     "mechanism": "Dual anticoagulant + antiplatelet effect.",
     "recommendation": "Monitor for bleeding. Use PPI. Common in high-risk COVID-19 protocols.",
     "source": "DDInter"},
]

# Common Indian combination brands (fixed-dose combos) with DDI risk
INDIAN_COMBO_INTERACTIONS = [
    {"drug_a": "Amlodipine", "drug_b": "Atenolol", "severity": "moderate",
     "description": "Common fixed-dose combination in India. Risk of bradycardia, especially in elderly.",
     "mechanism": "Additive cardiac depression — CCB blocks Ca++ entry + beta-blocker reduces HR.",
     "recommendation": "Monitor HR and BP. Avoid in patients with heart block or bradycardia.",
     "source": "DDInter"},
    {"drug_a": "Metformin", "drug_b": "Glimepiride", "severity": "moderate",
     "description": "Common Indian FDC. Additive hypoglycemia risk when doses escalated.",
     "mechanism": "Biguanide + sulfonylurea — dual glucose-lowering.",
     "recommendation": "Start at lowest dose. Monitor fasting glucose. Educate on hypoglycemia.",
     "source": "DDInter"},
    {"drug_a": "Atorvastatin", "drug_b": "Fenofibrate", "severity": "moderate",
     "description": "Common in diabetic dyslipidemia. Myopathy risk with high doses.",
     "mechanism": "Additive effect on muscle.",
     "recommendation": "Monitor CK. Avoid in renal impairment. Use fenofibrate, not gemfibrozil.",
     "source": "DrugBank"},
]

ALL_INTERACTIONS = INTERACTIONS + INDIAN_COVID_INTERACTIONS + INDIAN_COMBO_INTERACTIONS


class Command(BaseCommand):
    help = "Seed Indian-generic drug-drug interactions"

    def handle(self, *args, **options):
        created = 0
        skipped = 0
        for data in ALL_INTERACTIONS:
            _, was_created = DrugInteraction.objects.get_or_create(
                drug_a__iexact=data["drug_a"],
                drug_b__iexact=data["drug_b"],
                defaults=data,
            )
            if was_created:
                created += 1
            else:
                skipped += 1

        self.stdout.write(self.style.SUCCESS(
            f"Done! Created {created} Indian-generic DDI entries, {skipped} already existed."
        ))
